import type { DeskFile } from "@/lib/desk-file";

/** Pre-biblical contact traditions: Anunnaki, Watchers, flood teachers, theophanies. */
export const ANCIENT_FILES_CONTACT: DeskFile[] = [
  {
    id: "anunnaki-council",
    title: "Anunnaki — the great gods",
    kicker: "c. 2500–600 BCE texts",
    subtitle: "Sumer / Akkad / Babylon · Anunna, Anunnaki",
    lede: "In the cuneiform, the Anunnaki are the great gods of heaven and earth — not a mining corporation from Nibiru. The contact file is how later readers welded those names to sky-people.",
    summary:
      "Anunna / Anunnaki appear in Sumerian, Akkadian and Babylonian texts as a class of high gods under Anu. They judge, they assign destinies, they receive offerings. Igigi are often the junior gods. Zecharia Sitchin’s 1970s reading — Anunnaki as gold-mining astronauts who genetically engineered Homo sapiens — is a modern English overlay. Assyriology does not translate ‘Anunnaki’ as ‘those who from heaven to earth came’ in that sense. The desk files both: the real divine council, and the 20th-century contact myth built on it.",
    body: "Keep the names. Drop the planet unless a tablet names one. What the texts actually give you is a pantheon that comes down, teaches kingship, and floods the workers when they get too noisy. That is already a contact story. It does not need a twelfth planet to be strange.",
    evidence: "Standard editions of Enūma Eliš, Atra-ḫasīs, Inanna’s Descent, and god lists. Sitchin’s The 12th Planet as a separate modern corpus, not a translation.",
    sources: [
      "Jeremy Black & Anthony Green, Gods, Demons and Symbols of Ancient Mesopotamia",
      "Thorkild Jacobsen, The Treasures of Darkness",
      "Zecharia Sitchin, The 12th Planet (modern contact reading)",
    ],
    lat: 32.542,
    lng: 44.421,
    place: "Babylon",
    country: "Iraq",
    year: -1800,
  },
  {
    id: "enki-me",
    title: "Enki and the ME",
    kicker: "c. 2000 BCE copies",
    subtitle: "Eridu · civilizing decrees",
    lede: "Enki of the Abzu hands the ME — the arts of kingship, writing, weaving, law — to Inanna. Contact literature reads a technology transfer. The poem reads a god who drinks too much and gives the city its crafts.",
    summary:
      "In Inanna and Enki, the god of fresh water and cunning at Eridu possesses the ME (divine powers/offices): music, metal, scribal art, truth, descent to the netherworld. Inanna gets him drunk and boats them to Uruk. Alternative history treats the ME as a catalog of off-world tech. The tablet is a myth of how culture moves from the first city to the next. Eridu’s temple sequence is archaeological; the boat of heaven is not a recovered craft.",
    body: "If you want a Sumerian ‘download from the gods,’ this is the file. It is also a story about a clever goddess and a wet god. Both readings sit on the same lines.",
    evidence: "Composite text of Inanna and Enki; Eridu temple excavations. No object labelled ME in a lab.",
    sources: [
      "ETCSL, Inanna and Enki",
      "Safar, Mustafa & Lloyd, Eridu",
    ],
    lat: 30.816,
    lng: 45.996,
    place: "Eridu",
    country: "Iraq",
    year: -2000,
  },
  {
    id: "enlil-nippur",
    title: "Enlil of Nippur",
    kicker: "c. 2500–1200 BCE",
    subtitle: "Nippur · lord of the command",
    lede: "Enlil holds the Tablet of Destinies. He decrees the flood. Sitchin casts him as the harsh commander of the Anunnaki mission. The city of Nippur was his actual cult centre.",
    summary:
      "Enlil (‘Lord Wind’) is the executive god of the Sumerian pantheon, seated at Ekur in Nippur. Kings needed his endorsement. In Atra-ḫasīs he is the one who cannot sleep for the noise of humans and orders plague, drought, then flood. Contact writers split Enlil (order, cull) against Enki (mercy, leak of the flood warning). Nippur is a real tell with a long temple sequence. The family feud of gold-mining brothers is not in the Akkadian.",
    body: "A god who sends a flood because the workers are loud is already a dark contact story. Adding a chain-of-command from Nibiru is extra.",
    evidence: "Ekur excavations; Enlil hymns; Atra-ḫasīs flood sequence.",
    sources: [
      "McGuire Gibson, Nippur publications",
      "Lambert & Millard, Atra-ḫasīs",
    ],
    lat: 32.126,
    lng: 45.232,
    place: "Nippur",
    country: "Iraq",
    year: -2100,
  },
  {
    id: "ninhursag-clay",
    title: "Ninhursag — humans from clay",
    kicker: "Atra-ḫasīs / Enki and Ninmah",
    subtitle: "Sumer · the making of lulu",
    lede: "Gods mix clay with the blood of a slain god and bake workers. That is the Sumerian creation of humankind. The contact reading is a lab. The tablet is a birth goddess and a mix.",
    summary:
      "In Enki and Ninmah and in Atra-ḫasīs, lesser gods strike over the labour of digging canals. Enki and the mother-goddess (Ninhursag / Mami / Nintu) form humans from clay and divine blood so the gods can rest. Sitchin and later ancient-astronaut media recast this as genetic engineering of Homo sapiens as a slave species. Cuneiformists read a theogonic work-myth, cousin to Genesis 2’s clay, not a CRISPR protocol.",
    body: "Clay plus blood is the oldest factory floor in writing. Whether you hear a goddess or a gene-lab depends on which century you stand in.",
    evidence: "Standard Atra-ḫasīs and Enki and Ninmah; no ‘hybrid bone’ labelled as such in a Mesopotamian grave.",
    sources: [
      "Lambert & Millard, Atra-ḫasīs",
      "ETCSL, Enki and Ninmah",
    ],
    lat: 32.126,
    lng: 45.232,
    place: "Nippur / Eridu tradition",
    country: "Iraq",
    year: -1700,
  },
  {
    id: "igigi-revolt",
    title: "Igigi revolt",
    kicker: "Atra-ḫasīs I",
    subtitle: "The junior gods put down their baskets",
    lede: "Before humans, the Igigi dig the rivers for forty years, then burn their tools. Humans are invented as replacement labour. Contact files call it a mining strike.",
    summary:
      "Tablet I of Atra-ḫasīs opens with junior gods (Igigi) doing the corvée of the great gods, then revolting at Enlil’s gate. The solution is not better hours. It is a new species to carry the basket. Ancient-astronaut literature maps this onto Anunnaki gold mines and a workers’ mutiny. The Akkadian is about canal-digging and noise. The structure — sky-beings, exhausted labour, manufactured humans — is why the file lives on this desk.",
    body: "A strike in heaven that produces mankind is the contact skeleton. Gold and Nibiru are later clothing.",
    evidence: "Atra-ḫasīs I; god-class distinctions Anunna/Igigi in lexical lists.",
    sources: [
      "Lambert & Millard, Atra-ḫasīs",
      "Bottéro, Mesopotamia: Writing, Reasoning, and the Gods",
    ],
    lat: 32.542,
    lng: 44.421,
    place: "Babylonian copies",
    country: "Iraq",
    year: -1700,
  },
  {
    id: "apkallu-sages",
    title: "Apkallu — the seven sages",
    kicker: "c. 1800–700 BCE",
    subtitle: "Eridu · fish-cloaked teachers",
    lede: "Seven sages, first among them Adapa of Eridu, rise from the water before the flood to teach the crafts. They are the Sumerian Watchers, in another language.",
    summary:
      "Mesopotamian tradition names seven apkallu — sage-advisers who served antediluvian kings, often shown as fish-cloaked genies (kulullû) on Neo-Assyrian palace walls. Berossus later calls the first one Oannes. They teach writing, law, and city-building, then the flood comes and later sages are only ‘of human descent.’ Contact literature treats them as amphibious instructors. Assyriology treats them as a myth of how civilisation was founded once, from the deep.",
    body: "Teachers from the water, before the flood, who do not stay. That is the same plot as Enoch’s Watchers, with the moral inverted: these ones are authorised.",
    evidence: "Bit mēseri list of sages; palace reliefs; Berossus via later excerpts. No fish-man skeleton.",
    sources: [
      "Helge Kvanvig, Primeval History: Babylonian, Biblical, and Enochic",
      "Wiggermann, Mesopotamian Protective Spirits",
    ],
    lat: 30.816,
    lng: 45.996,
    place: "Eridu",
    country: "Iraq",
    year: -1500,
  },
  {
    id: "oannes-berossus",
    title: "Oannes",
    kicker: "3rd c. BCE report of older myth",
    subtitle: "Persian Gulf · the fish-man who taught by day",
    lede: "Berossus says a creature named Oannes came from the Erythraean Sea, taught the arts all day, and went back into the water at night. It is the most explicit pre-biblical contact report in Greek.",
    summary:
      "The Babylonian priest Berossus, writing in Greek for the Seleucid court, describes Oannes (from Akkadian Uanna / Adapa): a being with a fish body and a human voice who appeared in the first year, taught letters, sciences, and city law, then returned to the sea at sunset. He ate nothing. Later similar beings followed. Ancient-astronaut writers take this as a field report of an amphibious visitor. Classicists take it as Berossus packaging the apkallu for Greeks.",
    body: "A teacher who will not eat your food and sleeps in the gulf is a contact file whether or not you add a craft. The original tablets behind Berossus are lost; we have excerpts in Syncellus and others.",
    evidence: "Berossus fragments (Schnabel / Verbrugghe-Wickersham); apkallu iconography.",
    sources: [
      "Berossus, Babyloniaca (fragments)",
      "Gerald Verbrugghe & John Wickersham, Berossos and Manetho",
    ],
    lat: 30.5,
    lng: 47.8,
    place: "Head of the Persian Gulf",
    country: "Iraq",
    year: -280,
  },
  {
    id: "adapa",
    title: "Adapa — the failed immortality",
    kicker: "c. 1400 BCE copies",
    subtitle: "Eridu to Anu’s heaven",
    lede: "The sage of Eridu breaks the South Wind’s wing, is summoned to heaven, and is tricked out of the food of life. A man walks into the sky and comes back mortal.",
    summary:
      "Adapa, apkallu of Eridu, is called to Anu’s heaven after disabling the wind. Enki tells him not to eat. Anu offers the bread and water of life; Adapa refuses; he is sent home still mortal, and mankind stays so. Contact readings treat the ascent as an orbital interview. The poem is about a leaked invitation to immortality and a god who did not want his priest to become his peer.",
    body: "Ascent, interview, food that would change the body, a handler who lies. That is the contact grammar. It is also a wisdom tale about why we die.",
    evidence: "Amarna tablet EA 356 and later fragments; no ‘heavenly gate’ architecture at Eridu.",
    sources: [
      "Shlomo Izre'el, Adapa and the South Wind",
      "Amarna corpus",
    ],
    lat: 30.816,
    lng: 45.996,
    place: "Eridu",
    country: "Iraq",
    year: -1400,
  },
  {
    id: "nibiru-sitchin",
    title: "Nibiru / Planet of the crossing",
    kicker: "astral name vs 1976 book",
    subtitle: "Babylonian astronomy · Sitchin’s twelfth planet",
    lede: "Nēbiru in Akkadian is a crossing, often Jupiter or a name of Marduk as a star. Sitchin made it a 3,600-year planet that ferries Anunnaki. Astronomy has not found that orbit.",
    summary:
      "In Babylonian celestial omen texts, nēbiru is a ‘crossing’ point or a planet (commonly Jupiter) associated with Marduk. Zecharia Sitchin argued it was a large undiscovered body on a 3,600-year ellipse whose inhabitants, the Anunnaki, mined gold on Earth. No cuneiformist accepts his etymologies. No solar-system survey has produced a planet on that period. The file exists because the word is real and the modern story is still the loudest Anunnaki export.",
    body: "Do not confuse a Babylonian planetary alias with a recovered ephemeris. If a trans-Neptunian body is ever found, it will not arrive with Sitchin’s footnotes.",
    evidence: "MUL.APIN and planetary omens; NASA/minor-planet surveys; Sitchin as modern literature.",
    sources: [
      "Hermann Hunger & David Pingree, Astral Sciences in Mesopotamia",
      "Michael Heiser, critiques of Sitchin etymology",
    ],
    lat: 32.542,
    lng: 44.421,
    place: "Babylon",
    country: "Iraq",
    year: -700,
  },
  {
    id: "utnapishtim",
    title: "Utnapishtim / Ziusudra",
    kicker: "flood survivor",
    subtitle: "Mouth of the rivers · the man who did not die",
    lede: "A king is warned by a god, builds a boat, rides out a flood, and is placed at the edge of the world, alive forever. Gilgamesh goes to ask him why.",
    summary:
      "Ziusudra (Sumerian), Atra-ḫasīs, and Utnapishtim (Epic of Gilgamesh XI) are the Mesopotamian flood survivors. Enki leaks Enlil’s plan. The boat is built to a measured plan. After landing, the survivor is withdrawn to Dilmun or ‘the mouth of the rivers’ and given life like the gods. Genesis 6–9 is the Hebrew cousin. Contact readings treat the warning as radio from a faction of the Anunnaki. The tablets treat it as a god who will not let his city die.",
    body: "The oldest flood file on this desk. Pre-biblical, measured, and still the template for every later ark.",
    evidence: "Gilgamesh XI (Library of Ashurbanipal); Atra-ḫasīs III; Eridu Genesis. Flood silt in Mesopotamian tells is local, not global.",
    sources: [
      "Andrew George, The Babylonian Gilgamesh Epic",
      "Lambert & Millard, Atra-ḫasīs",
    ],
    lat: 30.4,
    lng: 47.9,
    place: "Mouth of the rivers / Dilmun tradition",
    country: "Iraq / Bahrain",
    year: -1200,
  },
  {
    id: "watchers-enoch",
    title: "The Watchers — 1 Enoch",
    kicker: "c. 300–100 BCE (older tradition)",
    subtitle: "Second Temple · Book of the Watchers",
    lede: "Two hundred angels descend, take wives, teach forbidden arts, and sire giants. Heaven sends a flood to wipe the experiment. This is the pre-biblical contact document the churches later sidelined.",
    summary:
      "1 Enoch 1–36 (Book of the Watchers) is a Second Temple Jewish work, fully preserved in Ge‘ez, with Aramaic fragments at Qumran. The Watchers (ʿîrîn) are heavenly beings assigned to watch the earth. They abandon their station, mate with human women, and teach metallurgy, cosmetics, astrology, and root-cutting. Their children are the giants. Enoch is taken up as a scribe of the lawsuit against them. Ancient-astronaut and ufology writers treat this as a landing and a hybrid program. Scholars treat it as an expansion of Genesis 6 plus Mesopotamian sage-myths, recast as a fall.",
    body: "Authorised watchers who go native, leak tech, and spawn a giant problem: that is the Watcher file. It is older than the New Testament and was scripture at Qumran. It is not in most Bibles. That absence is part of the file.",
    evidence: "4Q201–202 and other Qumran Enoch; Ge‘ez corpus; no giant cemetery that matches the numbers.",
    sources: [
      "George Nickelsburg, 1 Enoch 1",
      "James VanderKam, Enoch: A Man for All Generations",
      "4QEnoch fragments, DJD",
    ],
    lat: 31.741,
    lng: 35.459,
    place: "Qumran / Judean desert",
    country: "West Bank",
    year: -200,
  },
  {
    id: "hermon-descent",
    title: "Descent on Mount Hermon",
    kicker: "1 Enoch 6",
    subtitle: "Anti-Lebanon range · the oath of the 200",
    lede: "The Watchers land on Mount Hermon, bind themselves with an oath, and the mountain is named for the curse they take. A named peak, a named count, a named pact.",
    summary:
      "1 Enoch 6 says Shemihazah and two hundred Watchers descend in the days of Jared on Mount Hermon (Ḥermōn), swear, and then take wives. Later tradition maps the peak as a gate between worlds. Hermon is a real massif with high-altitude temples (including a Roman sanctuary) and a long cult history. Contact literature treats the descent as a literal landing site. Archaeology treats Hermon as a sacred high place, not a pad.",
    body: "If the Watchers had a coordinate, this is it. Bring a coat. The snow is older than the book.",
    evidence: "1 Enoch 6; cult remains on Hermon; no stratified ‘landing’ layer.",
    sources: [
      "1 Enoch 6–8",
      "Dar & others, Hermon temple surveys",
    ],
    lat: 33.416,
    lng: 35.857,
    place: "Mount Hermon",
    country: "Lebanon / Syria / Israel",
    year: -250,
  },
  {
    id: "nephilim",
    title: "Nephilim",
    kicker: "Genesis 6:4 / Numbers 13",
    subtitle: "The fallen / the giants in the land",
    lede: "The Nephilim are ‘on the earth in those days, and also afterward.’ Numbers’ spies say they felt like grasshoppers beside them. Hebrew is tight. Later books make them the Watchers’ sons.",
    summary:
      "Genesis 6:1–4 is four verses: sons of God, daughters of men, Nephilim, men of name. The Hebrew root npl (‘to fall’) is the usual etymology, not a species label. Numbers 13 puts Nephilim in Canaan as Anakim. 1 Enoch and Jubilees fill the blank with giant children of Watchers whose flesh-eating brings the flood. Ufology files them as hybrids. The desk files a short, old, unresolved line that every later giant story drinks from.",
    body: "Four verses did more work than most epics. Do not pretend they are a lab report. Do not pretend they are nothing.",
    evidence: "MT/LXX Genesis 6; Numbers 13; 1 Enoch 7; no diagnostic ‘Nephilim’ genome.",
    sources: [
      "Genesis 6:1–4",
      "Numbers 13:32–33",
      "P. W. Coxon, ‘Nephilim’ in Dictionary of Deities and Demons",
    ],
    lat: 31.768,
    lng: 35.214,
    place: "Judean highlands",
    country: "Israel",
    year: -900,
  },
  {
    id: "azazel-arts",
    title: "Azazel — the arts that were not to be taught",
    kicker: "1 Enoch 8",
    subtitle: "Weapons, adornment, dyes, seeing-stones",
    lede: "Azazel teaches swords, breastplates, mirrors, antimony, and the cutting of roots. The flood is, in part, a tech-ban. Contact files call it a prohibited knowledge drop.",
    summary:
      "In 1 Enoch 8 Azazel (and other named Watchers) teach metallurgy of weapons, cosmetics, jewellery, alchemy of minerals, astrology, and signs. The complaint in heaven is that the earth is ruined by leaked craft. Leviticus 16’s scapegoat ‘for Azazel’ is a separate, older ritual name that Enochic writers pin to this teacher. Ancient-astronaut readings map the list onto a cargo-cult of tools. Historians map it onto a Second Temple anxiety about war, sex, and foreign wisdom.",
    body: "A named instructor, a named curriculum, a named punishment (buried under desert rock until judgment). That is a contact dossier even if the instructor is an angel.",
    evidence: "1 Enoch 8–10; Leviticus 16; later desert-demon lore. No Azazel workshop layer.",
    sources: [
      "1 Enoch 8–10",
      "Grabbe, ‘The Scapegoat Tradition’",
    ],
    lat: 31.76,
    lng: 35.35,
    place: "Judean wilderness (Azazel tradition)",
    country: "West Bank",
    year: -200,
  },
  {
    id: "shemihazah",
    title: "Shemihazah and the two hundred",
    kicker: "1 Enoch 6–7",
    subtitle: "Chief of the descent",
    lede: "Shemihazah (Semjaza) is the Watcher who proposes the oath. He is not a demon in the later sense. He is a commander who wants bodies.",
    summary:
      "Shemihazah leads the pact on Hermon. The Book of Watchers lists chiefs in twenties and names their teachings. He takes a wife; the giant line begins. Later magic bowls and Enochic expansions keep the name. Contact literature treats him as expedition lead. The text treats him as the one who said ‘I will be guilty’ out loud so the others would jump.",
    body: "Command responsibility in a descent story. File him next to Enlil: different culture, same rank problem.",
    evidence: "1 Enoch 6–7 name-lists; later Aramaic magic texts.",
    sources: [
      "1 Enoch 6–7",
      "Nickelsburg, 1 Enoch 1",
    ],
    lat: 33.416,
    lng: 35.857,
    place: "Mount Hermon",
    country: "Lebanon / Syria / Israel",
    year: -200,
  },
  {
    id: "book-of-giants",
    title: "Book of Giants",
    kicker: "c. 200–50 BCE",
    subtitle: "Qumran · the children have names",
    lede: "The giants dream of a tablet washed clean and send Enoch a petition. This is the Watcher sequel the Bible never bound.",
    summary:
      "The Book of Giants, known from Qumran Aramaic fragments and later Manichaean versions, names Watcher-children (including Ohyah, Hahyah, Mahaway, and in some reconstructions Gilgamesh and Ḥobabish). They foresee the flood in dreams. Enoch interprets. Contact and fringe writers seize on the Gilgamesh name as proof of a shared antediluvian roster. Scholars see Second Temple Jews working Mesopotamian giant-lore into Enochic judgment.",
    body: "When the hybrid children get a voice, they sound afraid. That is the file. It is not a war report from a mothership. It is a dream of erasure.",
    evidence: "4Q530–533; Manichaean Book of Giants (Middle Persian, Sogdian). No giant osteology attached.",
    sources: [
      "L. Stuckenbruck, The Book of Giants from Qumran",
      "J. C. Reeves, Jewish Lore in Manichaean Cosmogony",
    ],
    lat: 31.741,
    lng: 35.459,
    place: "Qumran",
    country: "West Bank",
    year: -100,
  },
  {
    id: "genesis-6",
    title: "Sons of God — Genesis 6",
    kicker: "Torah",
    subtitle: "The shortest contact paragraph in the Bible",
    lede: "‘The sons of God saw that the daughters of humans were beautiful…’ Four verses, then the flood. Everything Watcher, Nephilim, and giant walks out of this door.",
    summary:
      "Genesis 6:1–4 is the Hebrew Bible’s only clear pre-flood mixed-descent notice. Early Jewish and Christian readers (1 Enoch, Justin, Tertullian) took ‘sons of God’ as angels. Later rabbinic and many modern readers take them as the line of Seth, or as kings. The contact desk files the angelic reading because that is the one the Enochic libraries ran with, and because the verse sits immediately before the flood as cause.",
    body: "If you only keep one pre-biblical contact slip from the Bible, keep this one. The rest of the Watcher library is commentary.",
    evidence: "Masoretic Text; Septuagint ἄγγελοι τοῦ θεοῦ in some witnesses; 1 Enoch as reception.",
    sources: [
      "Genesis 6:1–4",
      "R. Hendel, ‘The Nephilim Were on the Earth’",
    ],
    lat: 31.778,
    lng: 35.235,
    place: "Jerusalem (text tradition)",
    country: "Israel",
    year: -800,
  },
  {
    id: "jubilees-watchers",
    title: "Jubilees — Watchers as teachers first",
    kicker: "c. 160 BCE",
    subtitle: "They were sent to instruct, then they fell",
    lede: "Jubilees says God sent the angels to earth to teach humankind, and the fall came after the posting. That is a different brief from 1 Enoch’s mutiny.",
    summary:
      "The Book of Jubilees retells Genesis with a calendar and a stronger Watcher subplot: the angels of the Lord come down to instruct men, then take wives, and the giants follow. It makes the descent originally authorised — closer to apkallu than to a prison-break. Ethiopian Orthodoxy kept Jubilees. Most canons did not. Contact readers notice the ‘sent to teach’ clause immediately.",
    body: "Authorised instructors gone native. File beside Oannes and the apkallu. Three cultures, one job description.",
    evidence: "Jubilees 4–7; Qumran Jubilees copies; Ge‘ez Bible.",
    sources: [
      "James VanderKam, The Book of Jubilees",
      "4QJubilees",
    ],
    lat: 31.741,
    lng: 35.459,
    place: "Qumran / Ethiopia (preservation)",
    country: "West Bank",
    year: -160,
  },
  {
    id: "elohim-council",
    title: "Elohim and the Divine Council",
    kicker: "Psalm 82 / Deuteronomy 32",
    subtitle: "Most High divides the nations",
    lede: "Elohim can mean God, gods, or a class. Psalm 82 has the Most High judging other elohim. Deuteronomy 32 (Dead Sea reading) has him allot nations to the sons of God. Pre-biblical Israel had a council, not a solo.",
    summary:
      "Hebrew Bible passages preserve a divine-council picture: El Elyon, sons of God, allotted nations, Yahweh as Israel’s portion. Psalm 82 sentences the other gods to die like men. Ugaritic tablets show the same furniture (El, the seventy sons, the mountain of assembly). Contact and Mormon-adjacent readings treat the council as a board of sky-beings. Academic reading treats it as West Semitic theism that later monotheism compressed.",
    body: "A board of named powers over nations is a contact map if you want one. It is also how the Late Bronze Levant talked about gods. Both can be true in the file.",
    evidence: "Psalm 82; Deut 32:8 in 4QDeutj / LXX; KTU Ugaritic council scenes.",
    sources: [
      "Michael Heiser, The Unseen Realm (council reading)",
      "Mark S. Smith, The Origins of Biblical Monotheism",
    ],
    lat: 31.778,
    lng: 35.235,
    place: "Jerusalem / Ugarit parallel",
    country: "Israel",
    year: -700,
  },
  {
    id: "ugarit-council",
    title: "Ugarit — El’s mountain assembly",
    kicker: "c. 1300 BCE",
    subtitle: "Ras Shamra · the tablets under the tell",
    lede: "Before Genesis was bound, Ugarit already had El the bull, seventy sons, Baal the cloud-rider, and a mountain where the gods meet. Pre-biblical contact furniture, in clay.",
    summary:
      "The cuneiform alphabetic tablets from Ugarit (Ras Shamra, Syria) describe El at the source of the two deeps, a divine family, Baal’s struggle with Sea and Death, and assembly on the mountain. Biblical poetry borrows the cloud-rider, the sea-combat, the council. Ancient-astronaut overlays are unnecessary: this is the local operating system of Levantine gods. It is the soil Genesis 6 and Psalm 82 grow in.",
    body: "If you want Watchers without Ethiopia, start here. The mountain and the sons are already at the table.",
    evidence: "KTU / Ras Shamra publications; destruction layer c. 1200 BCE.",
    sources: [
      "N. Wyatt, Religious Texts from Ugarit",
      "Mark S. Smith, The Ugaritic Baal Cycle",
    ],
    lat: 35.602,
    lng: 35.785,
    place: "Ras Shamra (Ugarit)",
    country: "Syria",
    year: -1300,
  },
  {
    id: "ezekiel-wheels",
    title: "Ezekiel’s wheels",
    kicker: "c. 593 BCE",
    subtitle: "Kebar canal · merkabah",
    lede: "Wheels within wheels, rims full of eyes, a throne above a dome, a figure of amber fire. Ufology’s favourite prophet. Also the seed of Jewish merkabah mysticism.",
    summary:
      "Ezekiel 1 describes a storm-cloud theophany by the Kebar in exile: four living creatures, intersecting gyres, a crystal vault, a sapphire throne. Ancient-astronaut media (von Däniken, Blumrich’s The Spaceships of Ezekiel) reads a landing craft. Jewish tradition reads the chariot of the Glory and later builds a whole mysticism (merkabah) that warns you not to look too long. Engineers have drawn turbines from the Hebrew; Hebraists draw storm, cherubim, and Babylonian throne-iconography.",
    body: "The chapter is supposed to knock you down. File it as contact if you must. File it as the most dangerous vision in the prophets if you are being careful. Do not flatten it into a NASA diagram.",
    evidence: "Ezekiel 1 and 10; no wreckage on the Kebar. Blumrich is a modern engineer reading a prophet, not the reverse.",
    sources: [
      "Ezekiel 1; 10",
      "Josef Blumrich, The Spaceships of Ezekiel (contact reading)",
      "Halperin, The Faces of the Chariot",
    ],
    lat: 32.5,
    lng: 44.4,
    place: "Kebar canal, Babylonia",
    country: "Iraq",
    year: -593,
  },
  {
    id: "elijah-chariot",
    title: "Elijah’s chariot",
    kicker: "c. 9th c. BCE story",
    subtitle: "East of the Jordan · taken, not buried",
    lede: "A chariot of fire and horses of fire, a whirlwind, and the prophet is gone. Elisha is left holding a cloak. The Bible’s cleanest abduction file.",
    summary:
      "2 Kings 2:11: Elijah is taken up by a fiery chariot in a whirlwind. He does not die in the narrative. Later Jewish and Christian hope waits for his return. Contact readings treat the chariot as a craft. The Deuteronomistic historians treat it as YHWH’s storm-vehicle, the same furniture as Psalm 68’s rides through the deserts. No tomb of Elijah is claimed in the text — that is the point.",
    body: "Taken alive. Witness on the ground. Object of fire. That is why this page stays on a UFO desk even when the scholars roll their eyes.",
    evidence: "2 Kings 2; later Malachi 4 expectation. No physical chariot.",
    sources: [
      "2 Kings 2:1–18",
      "Psalm 68:4, 17",
    ],
    lat: 31.837,
    lng: 35.546,
    place: "Jordan valley, east bank",
    country: "Jordan",
    year: -850,
  },
  {
    id: "sinai-theophany",
    title: "Sinai — the mountain that smoked",
    kicker: "Exodus 19–24",
    subtitle: "Horeb / Jebel Musa candidates",
    lede: "Cloud, fire, trumpet that grows louder, a mountain quaking, a people told not to touch. Pre-biblical storm-god contact at industrial volume.",
    summary:
      "Exodus 19–20 is a theophany with sound and heat: smoke as from a kiln, lightning, a ram’s-horn blast that does not stop, a voice. Midianite, volcanic, and ‘landing’ readings all exist. Traditional sites cluster in the south Sinai; some fringe maps put it in Arabia (Jabal Maqla / Har Karkom debates). Archaeology has not produced a campsite that ends the argument. The file is the encounter as written: a people at the foot of a mountain that behaves like a craft and like a volcano and like a god.",
    body: "Do not pick a hill just to win. Keep the sensory list. That list is why later Watcher and merkabah texts keep returning to fire on a peak.",
    evidence: "Exodus 19–24; Deuteronomy 4–5; no consensus archaeological camp.",
    sources: [
      "Exodus 19–20",
      "Har Karkom / south Sinai survey literature",
    ],
    lat: 28.539,
    lng: 33.975,
    place: "Jebel Musa (traditional)",
    country: "Egypt",
    year: -1200,
  },
  {
    id: "pillar-cloud",
    title: "Pillar of cloud and fire",
    kicker: "Exodus 13–14",
    subtitle: "The moving column that led the camp",
    lede: "By day a column of cloud, by night a column of fire, shifting to the rear when Egypt closes in. A guiding object with tactics.",
    summary:
      "Exodus describes a pillar that goes before Israel, then moves behind them at the sea, lighting one side and darkening the other. Contact literature reads a craft on station. Biblical theology reads the messenger of YHWH in the cloud. There is no third contemporary chronicle. The image is stable across the wilderness itinerary and later gets built into the Tabernacle’s cloud.",
    body: "A luminous column that takes the flank is a contact behaviour even inside a priestly sentence. File it. Do not invent a serial number.",
    evidence: "Exodus 13:21–22; 14:19–24; Numbers 9. No physical column.",
    sources: [
      "Exodus 13–14",
      "Numbers 9:15–23",
    ],
    lat: 30.0,
    lng: 32.6,
    place: "Isthmus of Suez (traditional route)",
    country: "Egypt",
    year: -1200,
  },
  {
    id: "ark-covenant",
    title: "Ark of the Covenant",
    kicker: "late 2nd millennium tradition",
    subtitle: "Gold box · seat · weapon · radio",
    lede: "A gold-covered chest that kills on contact, leads armies, and speaks from between the cherubim. Temple furniture, or a device with a handling protocol.",
    summary:
      "Exodus 25 specifies acacia, gold, rings, poles, a kapporet, and two cherubim. Narratives add lethal mishandling (Uzzah), Philistine tumours, and a role as a war palladium. Fringe files (including Nazi-occult and ancient-astronaut lists) treat it as a capacitor, a transmitter, or a nuclear object. No Ark has been recovered. Ethiopian tradition claims it at Aksum; that claim is not independently verified. The desk files the handling rules: poles, distance, death on touch.",
    body: "A box with an SOP is more interesting than a box with a rumour. Keep the SOP. Leave the reactor drawings in the 1970s paperbacks.",
    evidence: "Exodus 25; 1 Samuel 4–6; 2 Samuel 6. No laboratory Ark.",
    sources: [
      "Exodus 25:10–22",
      "1 Samuel 4–6",
      "R. Haran, Temples and Temple-Service in Ancient Israel",
    ],
    lat: 31.778,
    lng: 35.235,
    place: "Jerusalem / Shiloh tradition",
    country: "Israel",
    year: -1000,
  },
  {
    id: "anakim-rephaim",
    title: "Anakim, Rephaim, Og",
    kicker: "Numbers–Deuteronomy / Ugarit",
    subtitle: "Giants of the land · the dead kings who still sit",
    lede: "Anakim in the hill country, Rephaim in the texts of Ugarit as dead warrior-kings, Og of Bashan with an iron bed nine cubits long. Israel’s conquest stories are full of leftover bodies from an older order.",
    summary:
      "The Hebrew Bible inventories giant clans in Canaan and Transjordan: Anakim, Emim, Zamzummim, Rephaim. Og of Bashan is last of the Rephaim; his bed (or sarcophagus) is measured. At Ugarit, rpum are underworld figures, summoned. Contact and giant-hunter literature collapse all of this into a Nephilim occupancy map. Semitic philology sees a mix of legendary aboriginals, underworld cult, and conquest propaganda. Bashan’s megalithic dolmens are real and older than Israel.",
    body: "Dolmens plus a measured bed plus a word for dead kings: that is enough for a file. It is not a census of hybrids.",
    evidence: "Deut 3:11; Numbers 13; KTU Rephaim texts; Golan/Bashan dolmen fields.",
    sources: [
      "Deuteronomy 3:1–11",
      "Spronk, Beatific Afterlife in Ancient Israel and in the Ancient Near East",
    ],
    lat: 32.77,
    lng: 35.77,
    place: "Bashan / Golan",
    country: "Syria / Israel",
    year: -900,
  },
  {
    id: "jacob-ladder",
    title: "Jacob’s ladder — Bethel",
    kicker: "Genesis 28",
    subtitle: "A stair between worlds, with traffic",
    lede: "A stone for a pillow, a dream of a stair set on the earth and touching heaven, messengers going up and down, a voice at the top. He names the place House of El.",
    summary:
      "Genesis 28: Jacob at Luz/Bethel sees a sullam (stair/ramp, not necessarily a ladder) with mal’ākim in motion and YHWH above it. He anoints the stone. Contact readings treat it as a beam or a craft ramp. Ancient Near Eastern temples used processional stairs as an image of the link to heaven (ziggurat, ‘gate of the god’). Bethel becomes a royal sanctuary, later condemned by the prophets. The dream is the contact; the oil on the stone is the claim staked.",
    body: "Traffic, not just a light. That is why this page is here. A one-way vision would be piety. Up-and-down is a route.",
    evidence: "Genesis 28; later Bethel cult polemics in Amos and Kings. No stair foundation that matches the dream.",
    sources: [
      "Genesis 28:10–22",
      "H. C. Brichto on sullam",
    ],
    lat: 31.936,
    lng: 35.222,
    place: "Bethel (Beitin)",
    country: "West Bank",
    year: -900,
  },
  {
    id: "enoch-taken",
    title: "Enoch walked and was not",
    kicker: "Genesis 5:24 / 1 Enoch / 2 Enoch",
    subtitle: "The scribe who did not die",
    lede: "Seven words in Hebrew: Enoch walked with God, and he was not, for God took him. The Enochic libraries spend books explaining where.",
    summary:
      "Genesis 5:24 is the Bible’s other non-death. 1 Enoch makes him the heavenly scribe of the Watcher trial. 2 Enoch (Slavonic) walks him through ten heavens. 3 Enoch (Hebrew) turns him into Metatron, the lesser YHWH. Contact literature treats ‘took him’ as a lift. Mystical Judaism treats it as the prototype of ascent. Either way the man does not leave a grave in the story, and later writers cannot stop filling the gap.",
    body: "The shortest abduction in Torah, and the longest fan-tradition in the desert libraries. File both lengths.",
    evidence: "Genesis 5; 1 Enoch 12–16; 2 Enoch; 3 Enoch. No tomb cult of Enoch comparable to the patriarchs.",
    sources: [
      "Genesis 5:21–24",
      "1 Enoch 12–16",
      "Odeberg, 3 Enoch",
    ],
    lat: 31.741,
    lng: 35.459,
    place: "Qumran / Enochic tradition",
    country: "West Bank",
    year: -200,
  },
  {
    id: "thoth-teacher",
    title: "Thoth — measurer and scribe",
    kicker: "Old Kingdom onward",
    subtitle: "Hermopolis · the one who invented writing",
    lede: "Ibis or baboon, moon, words, medicine, the book. Later Greeks call him Hermes Trismegistus and let him teach the world. Egypt already had him as the inventor of letters.",
    summary:
      "Thoth (Djehuty) is the divine scribe, lord of the moon and of measurement, credited with writing, ritual knowledge, and the calming of the Distant Goddess. The later Hermetica (early centuries CE) turn him into a primordial teacher of cosmos and soul — a civilizing contact in Greek dress. Ancient-astronaut lists file Thoth as an instructor-being. Egyptology files a god of the scribal class whose cult city was Khemenu (Hermopolis). Both agree knowledge is said to have come from him, not from trial and error.",
    body: "When a culture says writing arrived as a gift, put it next to Enki’s ME and the Watchers’ curriculum. Different Nile, same claim.",
    evidence: "Pyramid Texts and later temple theologies; Hermetica as a much later corpus.",
    sources: [
      "Patrick Boylan, Thoth, the Hermes of Egypt",
      "Brian Copenhaver, Hermetica",
    ],
    lat: 27.781,
    lng: 30.804,
    place: "Hermopolis Magna (el-Ashmunein)",
    country: "Egypt",
    year: -2400,
  },
  {
    id: "pyramid-texts-stars",
    title: "Pyramid Texts — the king becomes a star",
    kicker: "c. 2350 BCE",
    subtitle: "Unas pyramid, Saqqara · oldest religious corpus",
    lede: "The walls tell the dead king to climb a ladder, board a boat, and rise among the Imperishable Stars. Pre-biblical spaceflight as ritual, in stone.",
    summary:
      "The Pyramid Texts of Unas and later Old Kingdom kings are the oldest substantial religious corpus on earth. They include sky-ladders, ferry-boats, cannibal hymns, and identification with Orion (Sah) and Sothis (Sopdet). Bauval’s Orion correlation is a modern overlay on a real stellar theology. Contact readers hear a launch. Egyptologists hear a king joining the northern circumpolar stars that do not die. The words are on the wall. The craft is not in the sand.",
    body: "You do not need von Däniken once you have Unas. The sky is already the destination.",
    evidence: "Unas pyramid inscriptions; later copies in coffins. No engine.",
    sources: [
      "James Allen, The Ancient Egyptian Pyramid Texts",
      "Unas pyramid epigraphy",
    ],
    lat: 29.868,
    lng: 31.215,
    place: "Saqqara, pyramid of Unas",
    country: "Egypt",
    year: -2350,
  },
  {
    id: "osiris-civilizer",
    title: "Osiris the civilizer",
    kicker: "Plutarch / older Egyptian cycle",
    subtitle: "He taught grain, law, then he was cut up",
    lede: "Plutarch’s Osiris travels the world teaching agriculture and law, then is murdered and reassembled. A civilizing visitor who does not get to stay.",
    summary:
      "Egyptian Osiris is lord of the dead and of grain. Plutarch’s De Iside (2nd c. CE, using older priestly lore) has him civilise the world with music and tillage before Seth kills him. Isis recovers the body. Contact and mystery-religion writers treat Osiris as a culture-bearer from elsewhere. Native texts already make him a dead king whose resurrection is the flood and the sprouting barley. The civilizing tour is the Greek-period polish on a much older dismemberment.",
    body: "Teacher, murder, reassembly, crops. Put him in the same drawer as Quetzalcoatl and Viracocha: the visitor who leaves a method and a wound.",
    evidence: "Pyramid Texts Osiris cycle; Plutarch, De Iside et Osiride; no ‘foreign’ Osiris tomb that is not Egyptian.",
    sources: [
      "Plutarch, De Iside et Osiride",
      "J. Gwyn Griffiths, The Origins of Osiris and His Cult",
    ],
    lat: 26.185,
    lng: 31.919,
    place: "Abydos",
    country: "Egypt",
    year: -2400,
  },
  {
    id: "viracocha-andes",
    title: "Viracocha — the walking teacher",
    kicker: "Andean cycle (Inca reports)",
    subtitle: "Tiahuanaco to the sea · staff, pale, bearded in some versions",
    lede: "A creator who makes people of stone, walks the highlands teaching, and leaves across the Pacific. Spanish ears heard a saint. Contact ears hear a visitor.",
    summary:
      "Colonial chronicles (Betanzos, Molina, Sarmiento, Garcilaso) record Viracocha (Wiraqucha) as a culture-bearer associated with Tiwanaku, a staff, and a departure westward over the water. Some versions add light skin and a beard — details that may be post-contact contamination. Archaeology of Tiwanaku does not require a foreign instructor. The walking-teacher pattern matches Quetzalcoatl, Oannes, and Osiris closely enough to live on this desk as a pre-modern contact type, not as a proof of Europeans in 800 CE.",
    body: "A god who walks, teaches, and leaves a lake is a file. A beard in a Spanish sentence is not a passport.",
    evidence: "16th-c. chronicles; Tiwanaku monumental core. No Veracruz-to-Titicaca workshop layer.",
    sources: [
      "Juan de Betanzos, Suma y narración de los Incas",
      "Tiwanaku excavation literature",
    ],
    lat: -16.555,
    lng: -68.673,
    place: "Tiwanaku",
    country: "Bolivia",
    year: 600,
  },
  {
    id: "quetzalcoatl-teacher",
    title: "Quetzalcoatl — the feathered instructor",
    kicker: "Tollan cycle",
    subtitle: "Tula / Cholula · wind, Venus, books, the exit east",
    lede: "A priest-king of Tollan who forbids heart-sacrifice in some versions, teaches the calendar and writing, and leaves on a raft of snakes toward the dawn. Cortés walked into the rumour.",
    summary:
      "Quetzalcoatl is at once a Venus god, a wind god, and a legendary ruler of Tollan (Tula) who departs east. Later sources (Sahagún, Annals of Cuauhtitlan) give him a civilizing brief and a shame-driven exile. Spanish invaders exploited a return prophecy that may have been sharpened after 1519. Ancient-astronaut and ‘white god’ literature strip the Mesoamerican theology and leave a visitor from the sky. Keep the temple at Tula and the Venus tables. Leave the blond spaceman.",
    body: "Instructor, taboo, eastward exit, Venus. That is a contact type native to Mesoamerica. It does not need a North Atlantic.",
    evidence: "Tula sculpture; Codex sources; Sahagún. Return-prophecy debate in conquest studies.",
    sources: [
      "Bernardino de Sahagún, Florentine Codex",
      "Nicholson, Topiltzin Quetzalcoatl",
    ],
    lat: 20.064,
    lng: -99.34,
    place: "Tula",
    country: "Mexico",
    year: 950,
  },
  {
    id: "saptarishi",
    title: "Saptarishi — the seven seers",
    kicker: "Vedic / Puranic",
    subtitle: "The seven who survive the flood with Manu",
    lede: "Seven sages, a boat, a fish that is a god, a world washed. India independently files the same furniture as Eridu and Enoch: authorised teachers plus a flood.",
    summary:
      "The Saptarishi are the seven great ṛṣis of Vedic and Puranic tradition, mapped onto the Big Dipper. In the flood story (Śatapatha Brāhmaṇa, later Matsya Purāṇa) Manu is warned by a fish (Matsya, a form of Viṣṇu), builds a boat, and ties it to the horn of the fish; the seven sages ride with him. Contact comparativists put them next to the apkallu. Indologists put them in a ritual-astronomy complex. The parallel is real as a type, not as a shared airline.",
    body: "Seven teachers, a warning animal, a measured boat. If you are collecting pre-biblical contact patterns, this is the Indic stamp.",
    evidence: "Śatapatha Brāhmaṇa 1.8.1; Matsya Purāṇa; no single ‘landing’ site.",
    sources: [
      "Śatapatha Brāhmaṇa, flood narrative",
      "Witzel on Manu and flood comparanda",
    ],
    lat: 29.96,
    lng: 78.16,
    place: "Badarikāśrama / Himalayan tradition",
    country: "India",
    year: -800,
  },
  {
    id: "manu-matsya",
    title: "Manu and the fish",
    kicker: "Śatapatha Brāhmaṇa",
    subtitle: "The first man is warned from the water",
    lede: "A small fish asks for protection, grows huge, and tows Manu’s ark to a northern mountain. Enki’s leak, in another river.",
    summary:
      "Manu finds a fish in his washing water. It speaks. He raises it until it fills the ocean. It tells him of a coming flood, orders a ship, and pulls him to a peak. The fish is later identified as Matsya, avatar of Viṣṇu. This is not a borrowing from Genesis on any timeline that puts the Brāhmaṇa late enough; it is a separate flood-warning-from-the-water. Contact desks file it with Oannes: knowledge comes out of the deep and does not stay.",
    body: "The warning is the contact. The mountain is just where the boat hits.",
    evidence: "Śatapatha Brāhmaṇa 1.8.1; later Puranic expansions.",
    sources: [
      "Śatapatha Brāhmaṇa 1.8.1",
      "Matsya Purāṇa 1–2",
    ],
    lat: 21.63,
    lng: 69.61,
    place: "Western ocean tradition / Prabhas",
    country: "India",
    year: -800,
  },
  {
    id: "etana-eagle",
    title: "Etana — the flight to heaven",
    kicker: "c. 1900–1500 BCE copies",
    subtitle: "Kish · a king rides an eagle into the sky",
    lede: "The king of Kish, childless, is carried by an eagle past the circles of heaven to ask for the plant of birth. He looks down, panics, and the tablet breaks. A manned ascent, in Akkadian.",
    summary:
      "The Etana epic has the king of Kish ally with a rescued eagle and fly toward the heaven of Anu for the plant of birth. Tablet copies describe the ground shrinking beneath them. The ending is fragmentary. Contact readers hear an aerial vehicle. Assyriologists hear a myth of royal legitimacy and a shamanic flight. Kish is a real early city. The eagle is not a recovered airframe.",
    body: "Ascent, shrinking earth, a missing last tablet. File it with Adapa: two Sumerian-Akkadian men who go up and do not get what they wanted.",
    evidence: "Old Babylonian and Neo-Assyrian Etana tablets; Kish excavations.",
    sources: [
      "J. V. Kinnier Wilson, The Legend of Etana",
      "Kish field publications",
    ],
    lat: 32.54,
    lng: 44.6,
    place: "Kish",
    country: "Iraq",
    year: -1800,
  },
  {
    id: "ziggurat-babil",
    title: "Etemenanki — the stair of Babylon",
    kicker: "c. 600 BCE rebuild (older foundation)",
    subtitle: "Babylon · house of the foundation of heaven and earth",
    lede: "A staged tower named as the link between heaven and earth. Genesis later remembers a city that tried to reach the sky and lost its words.",
    summary:
      "Etemenanki, Marduk’s ziggurat in Babylon, is named ‘House of the Foundation of Heaven and Earth.’ Herodotus describes a staged tower with a shrine on top. The E-sagil tablet gives dimensions. Genesis 11’s Babel is the Hebrew memory of that sky-stair and of imperial language. Contact literature treats ziggurats as landing platforms. Architecture treats them as staged temples with a high chapel, processions, and brick. Both agree the point of the building is traffic with above.",
    body: "A stair with a name that already says heaven-and-earth. Genesis did not invent the ambition. It judged it.",
    evidence: "E-sagil tablet; Koldewey’s Babylon; Herodotus I.181. No pad markings.",
    sources: [
      "Andrew George, Babylonian Topographical Texts",
      "Genesis 11:1–9",
    ],
    lat: 32.536,
    lng: 44.421,
    place: "Babylon",
    country: "Iraq",
    year: -600,
  },
  {
    id: "dead-sea-enoch",
    title: "Qumran — the Watcher library",
    kicker: "c. 250–50 BCE copies",
    subtitle: "Cave 4 · Enoch as scripture",
    lede: "The community by the Dead Sea kept multiple copies of Enoch and Jubilees. For them the Watchers were not folklore. They were the explanation of evil.",
    summary:
      "Among the Dead Sea Scrolls, 1 Enoch fragments (especially Book of Watchers and Astronomical Book) and Jubilees are not marginal. They sit with Torah. The Qumran community’s calendar, angelology, and origin-of-evil story run through the descent on Hermon. When later canons dropped Enoch, they dropped the main Jewish contact narrative of the Second Temple. This cave is why the Watchers survived to be read by Ethiopian monks and, much later, by ufologists.",
    body: "A desert library decided the Watchers were canon. Rome and Jamnia later disagreed. The fragments are still in the cave photographs.",
    evidence: "4Q201–212; 4QJubilees; community rule angelology.",
    sources: [
      "Discoveries in the Judaean Desert (DJD) Enoch volumes",
      "VanderKam, The Dead Sea Scrolls Today",
    ],
    lat: 31.741,
    lng: 35.459,
    place: "Qumran Cave 4",
    country: "West Bank",
    year: -100,
  },
];
