import type { DeskFile } from "@/lib/desk-file";

export const CONSPIRACY_FILES_CRYPTIDS: DeskFile[] = [
  {
    id: "bigfoot",
    title: "Bigfoot / Sasquatch",
    kicker: "1958–",
    subtitle: "Pacific Northwest · unknown primate file",
    lede: "A large biped in the temperate forest. The tracks and the 1967 film are real objects. The animal is not in the collection.",
    summary: "Sasquatch is the longest-running North American hairy-hominid file: Bluff Creek tracks in 1958, the Patterson–Gimlin film in 1967, later casts, thermal clips, and hair that usually comes back as known mammals. The Forest Service and several sheriffs have taken reports. No type specimen sits in a museum. The conspiracy version is that a body was recovered and buried in a federal freezer. The open record is tracks, film, and a species that has not been produced.",
    body: "Indigenous oral history of large forest people is older than the English name. The modern file begins when Jerry Crew’s 1958 Bluff Creek casts hit the papers and Ray Wallace later claimed a wooden fake. Patterson’s 16 mm reel survived every analog generation and still splits the desk: costume versus unknown primate. Hair, scat, and eDNA surveys have not closed it. A recovered body would end the argument. None has been produced under chain of custody.",
    evidence: "Confirmed: 1958–67 press, the Patterson reel as a physical film, dozens of casts, and USFS/sheriff incident notes. Unconfirmed: a body, a nesting site under study, or a classified recovery. Wallace’s hoax claim covers some tracks, not the whole geography.",
    sources: [
      "Patterson–Gimlin 16 mm film, 20 Oct 1967",
      "John Green / René Dahinden case collections",
      "U.S. Forest Service and county sheriff incident notes as later published",
    ],
    lat: 41.267,
    lng: -123.897,
    place: "Bluff Creek, California",
    country: "USA",
    year: 1967,
  },
  {
    id: "patterson-gimlin",
    title: "Patterson–Gimlin film",
    kicker: "1967",
    subtitle: "Bluff Creek · 16 mm reel",
    lede: "Fifty-two seconds of a biped turning at the camera. It is the cryptid file’s one durable artifact.",
    summary: "On 20 October 1967 Roger Patterson and Bob Gimlin filmed a female-looking biped at Bluff Creek. Frame 352 — the head turn — is the image the culture kept. Costume makers have claimed it; none has reproduced the gait, the sole flexion, and the muscle under the hair to a consensus. The film stock, the location, and Gimlin’s later interviews are on the record. The subject is not in a jar.",
    body: "A film can be a hoax and still be hard to rebuild. That is why this reel sits on the desk. Site surveys, tree measurements, and later digital enlargements have not produced a zipper. They have not produced a species either. Treat the reel as evidence of an event, not as a holotype.",
    evidence: "The camera original and copies exist. Location is surveyed. No studio wardrobe log has been authenticated as the source. No bones.",
    sources: [
      "Patterson–Gimlin film, 20 October 1967",
      "On-site measurements published by John Green and later analysts",
      "Bob Gimlin interviews",
    ],
    lat: 41.267,
    lng: -123.897,
    place: "Bluff Creek, California",
    country: "USA",
    year: 1967,
  },
  {
    id: "ape-canyon",
    title: "Ape Canyon",
    kicker: "1924",
    subtitle: "Mount St. Helens · miners’ siege",
    lede: "Fred Beck said apes stoned a cabin all night. The canyon kept the name. The bodies were never shown.",
    summary: "In July 1924, miners including Fred Beck reported being attacked at a cabin on the rim of Ape Canyon by large bipedal apes after one was shot. Rocks hit the roof until dawn. Portland papers ran it. The Forest Service and later St. Helens climbers reused the name. No skeleton, no 1924 official inquiry file that identifies the animals.",
    body: "A newspaper siege is not a specimen. Beck’s later spiritualist retellings weaken the first-night report without erasing it. The 1980 eruption rewrote the mountain. The file remains the earliest well-dated Pacific Northwest hominid flap with named witnesses and a map point.",
    evidence: "1924 Oregonian and wire coverage; Beck’s later pamphlet. No coroner’s record, no skins.",
    sources: [
      "Portland Oregonian, July 1924",
      "Fred Beck, I Fought the Apemen of Mount St. Helens",
    ],
    lat: 46.166,
    lng: -122.15,
    place: "Ape Canyon, Washington",
    country: "USA",
    year: 1924,
  },
  {
    id: "skunk-ape",
    title: "Skunk Ape",
    kicker: "1970s–",
    subtitle: "Florida wetlands · southern sasquatch",
    lede: "A foul-smelling biped in the cypress. The Myakka photographs are the exhibit. The zoo never got one.",
    summary: "Florida’s skunk ape is the southeastern hairy-hominid: Fakahatchee and Myakka reports, a 2000 pair of photographs mailed to the Sarasota sheriff, and a long list of swamp-buggy anecdotes. Skeptics prefer bear. The photographs show a dark face in vegetation. They do not show a body tag.",
    body: "A subtropical primate would be easier to catch than a Cascades one. That is the problem for the file. Decades of airboats and hunters have not produced a carcass that survives a lab. The smell is consistent in the reports. Smell is not a holotype.",
    evidence: "Sheriff’s office copies of the 2000 Myakka prints; FWC nuisance-bear explanations; no voucher specimen.",
    sources: [
      "Sarasota County Sheriff’s Office Myakka photographs, 2000",
      "Florida Fish and Wildlife public comments on bear misIDs",
    ],
    lat: 27.241,
    lng: -82.256,
    place: "Myakka River State Park, Florida",
    country: "USA",
    year: 2000,
  },
  {
    id: "fouke-monster",
    title: "Fouke Monster",
    kicker: "1971",
    subtitle: "Arkansas · Boggy Creek",
    lede: "A river-bottom biped that became a drive-in picture. The 1971 reports came first.",
    summary: "In 1971 the Ford family and other Fouke residents reported a large hairy figure around the Jonesville bottom. Footprints and a frightened household made the wires. Charles B. Pierce’s 1972 docudrama The Legend of Boggy Creek froze the story. Later sightings never produced a body. The town still sells the name.",
    body: "A successful regional film can overwrite the original night. Strip the soundtrack and you still have 1971 police and press notes from a real hamlet. That is enough to keep the file. It is not enough to name a species.",
    evidence: "1971 Texarkana Gazette and associated press; the 1972 film as popularization, not as evidence. No specimen.",
    sources: [
      "Texarkana Gazette, 1971 Fouke reports",
      "The Legend of Boggy Creek (1972) as cultural record",
    ],
    lat: 33.261,
    lng: -93.885,
    place: "Fouke, Arkansas",
    country: "USA",
    year: 1971,
  },
  {
    id: "honey-island",
    title: "Honey Island Swamp Monster",
    kicker: "1960s–",
    subtitle: "Pearl River, Louisiana · four-toed casts",
    lede: "Harlan Ford’s casts and a story of a grave. The swamp is real. The grave was never opened on camera.",
    summary: "The Honey Island file is a Louisiana biped with four-toed tracks, popularized by retired air-traffic controller Harlan Ford. He described a creature and, later, a buried carcass he did not recover under witnesses. Casts circulate. The Pearl River swamp is large enough to hide a bear and a story.",
    body: "Four toes are the diagnostic the believers cite against known black bear. Casts can be carved. Without a carcass or a sequenced hair with an unknown genome, the file stays a local legend with better props than most.",
    evidence: "Ford interviews and plaster casts in later documentaries. No peer-reviewed DNA, no bones.",
    sources: [
      "Harlan Ford interviews as later televised",
      "St. Tammany / Pearl River local press retrospectives",
    ],
    lat: 30.28,
    lng: -89.69,
    place: "Honey Island Swamp, Louisiana",
    country: "USA",
    year: 1974,
  },
  {
    id: "mothman",
    title: "Mothman",
    kicker: "1966–1967",
    subtitle: "Point Pleasant, West Virginia · winged figure",
    lede: "Red eyes on the TNT plant road. Then the bridge fell. John Keel wrote the American omen file.",
    summary: "From 12 November 1966 through December 1967, Point Pleasant residents — starting with the Scarberry and Mallette couples in the old WWII TNT area — reported a man-sized winged figure with glowing red eyes. Radio, police blotters, and the Athens Messenger logged it. On 15 December 1967 the Silver Bridge collapsed into the Ohio River and killed 46. John Keel tied the bird, the lights, and the disaster into The Mothman Prophecies. Ornithologists offered sandhill crane. The town kept the statue.",
    body: "A crane does not explain the breadth of the 13-month flap, and a flap does not prove a omen. Keel’s notebooks mix first-hand interviews with a Fortean thesis that the phenomenon is a control system, not a bird. The desk files the sightings, the TNT-area geography, and the bridge as three stacked records. Only the collapse is closed.",
    evidence: "1966–67 local press and police mentions; Keel’s published interviews; NTSB Silver Bridge report. No body, no photograph with chain of custody.",
    sources: [
      "Athens Messenger and Point Pleasant Register, Nov 1966–Dec 1967",
      "John A. Keel, The Mothman Prophecies (1975)",
      "NTSB report on the Silver Bridge collapse",
    ],
    lat: 38.881,
    lng: -82.137,
    place: "Point Pleasant, West Virginia",
    country: "USA",
    year: 1966,
  },
  {
    id: "silver-bridge",
    title: "Silver Bridge collapse",
    kicker: "1967",
    subtitle: "Ohio River · eyebar failure / omen argument",
    lede: "A 1928 eyebar chain bridge failed at rush hour. Engineering closed the cause. Folklore did not.",
    summary: "On 15 December 1967 the Silver Bridge between Point Pleasant, West Virginia, and Gallipolis, Ohio, collapsed, killing 46. The National Transportation Safety Board traced it to a single eyebar fracture from stress corrosion. Keel and later writers treated the Mothman year as a warning. The metallurgy does not require a winged witness. The coincidence is why the two files are still stapled together on this desk.",
    body: "A documented mechanical failure can sit beside a documented flap without either proving the other. That staple is the conspiracy: not that the NTSB lied, but that the year of reports is treated as irrelevant noise. Keep both papers.",
    evidence: "NTSB accident report is primary and uncontested as engineering. The omen claim is interpretive and not in the federal file.",
    sources: [
      "NTSB, Collapse of U.S. 35 Highway Bridge, Point Pleasant (1968/1971)",
      "Local death and recovery lists, December 1967",
    ],
    lat: 38.844,
    lng: -82.141,
    place: "Point Pleasant / Gallipolis",
    country: "USA",
    year: 1967,
  },
  {
    id: "indrid-cold",
    title: "Indrid Cold",
    kicker: "1966",
    subtitle: "Parkersburg, West Virginia · the Grinning Man",
    lede: "Woodrow Derenberger said a grinning stranger stopped his van on I-77 and spoke in his head. Keel named him.",
    summary: "On 2 November 1966, traveling salesman Woodrow Derenberger reported a dark craft and a smiling man — later called Indrid Cold — beside Interstate 77 near Parkersburg. He repeated the story on local radio and to Keel. The Grinning Man became a sister file to Mothman: same autumn, same river counties, same investigator. No second named witness placed Cold on the pavement that night.",
    body: "A single charismatic witness plus a novelist-investigator can mint a character that outlives the traffic stop. Derenberger’s later contactee elaborations are weaker than the first broadcast. The file stays because it is the human-looking face of the 1966 Ohio Valley wave, not because a badge was run.",
    evidence: "Derenberger radio/TV interviews, 1966; Keel’s notes. No police booking, no photograph of Cold.",
    sources: [
      "WTAP / local West Virginia interviews, November 1966",
      "John A. Keel, The Mothman Prophecies",
    ],
    lat: 39.267,
    lng: -81.562,
    place: "Parkersburg, West Virginia",
    country: "USA",
    year: 1966,
  },
  {
    id: "owlman",
    title: "Owlman of Mawnan",
    kicker: "1976",
    subtitle: "Cornwall · winged figure over the church",
    lede: "Two girls on holiday described a feathered humanoid above Mawnan church. The vicar asked them not to panic the parish.",
    summary: "In April 1976, and again that summer, witnesses around Mawnan Smith, Cornwall — beginning with the Melling sisters — reported a large owl-like figure with pointed ears and claws near the church. Tony ‘Doc’ Shiels collected drawings. Owlman is routinely filed as Britain’s Mothman. Owls exist in Cornwall. A 5-foot owl with hips does not, on the list of breeding birds.",
    body: "Shiels is a showman; that fact is in every sceptical write-up. It does not invent the Melling report. The file is a small, well-dated English winged-humanoid cluster with sketches. It is not a corpse in Truro.",
    evidence: "1976 Cornish press; Shiels’ published drawings; no photograph, no specimen.",
    sources: [
      "Cornish / West Briton coverage, 1976",
      "Later summaries in Fortean and owl-misidentification literature",
    ],
    lat: 50.102,
    lng: -5.127,
    place: "Mawnan Smith, Cornwall",
    country: "UK",
    year: 1976,
  },
  {
    id: "flatwoods-monster",
    title: "Flatwoods Monster",
    kicker: "1952",
    subtitle: "Braxton County, West Virginia · hooded figure",
    lede: "A burning object on the hill, a tall spade-headed shape in the trees, and a mist that made the search party sick.",
    summary: "On the night of 12 September 1952, Kathleen May, her sons, and National Guardsman Eugene Lemon climbed a hill above Flatwoods after a bright object appeared to land. They described a 10–12 foot figure with a spade-shaped hood, a stiff pleated skirt, and a sharp odor. Several became ill. Braxton County papers and a Project Blue Book card exist. The Air Force preferred a meteor and a barn owl. The monster is West Virginia’s other 1950s occupant file, a county over from where Mothman would later stand.",
    body: "An owl in a tree plus hysteria is the tidy close. It does not cover the reported landing light, the duration of the illness, or why the description (metallic skirt, cowl) was stable across the children and May. Blue Book filed it. This desk files it as a cryptid/occupant hybrid: a body with a craft, not a distant light.",
    evidence: "Braxton County press, September 1952; Blue Book card; later interviews with May. No photograph of the figure, no recovered hardware.",
    sources: [
      "Braxton Democrat / Braxton Central, Sept 1952",
      "Project Blue Book Flatwoods card",
      "Gray Barker’s contemporaneous notes",
    ],
    lat: 38.723,
    lng: -80.65,
    place: "Flatwoods, West Virginia",
    country: "USA",
    year: 1952,
  },
  {
    id: "van-meter",
    title: "Van Meter Visitor",
    kicker: "1903",
    subtitle: "Iowa · horned winged thing on the rooftops",
    lede: "A coal town shot at a bat-winged figure with a headlight in the forehead. The next night it came back.",
    summary: "On 29–30 September 1903, townsmen in Van Meter, Iowa, including a doctor and the bank cashier, reported a large winged creature with a blunt horn that threw light. They fired. An old mine shaft was the suspected roost. Des Moines and Chicago papers ran it. The visitor never became a national monster brand. The town minutes and the wires are why it is on the desk.",
    body: "A 1903 panic can be a crane, a hoax, or an unknown. What it is not is an internet invention. Primary newspapers exist. No skin was tanned in Dallas County.",
    evidence: "1903 Des Moines Register and associated wire stories; local commemorative records. No specimen.",
    sources: [
      "Des Moines newspapers, October 1903",
      "Van Meter historical society retrospectives",
    ],
    lat: 41.534,
    lng: -93.954,
    place: "Van Meter, Iowa",
    country: "USA",
    year: 1903,
  },
  {
    id: "grafton-monster",
    title: "Grafton Monster",
    kicker: "1964",
    subtitle: "West Virginia · white, seal-skinned biped",
    lede: "A newspaper editor said he hit the brakes for a pale, headless-looking hulk beside Route 119. He went back with a camera and a sheriff.",
    summary: "On 16 June 1964, Grafton Sentinel reporter Robert Cockrell reported a 7–9 foot pale creature with seal-like skin on a river road south of Grafton. He returned with law enforcement. Searches found impressions in the grass, not a body. West Virginia thus holds three occupant-adjacent files in twelve years: Flatwoods, Grafton, Mothman. They do not look like the same animal.",
    body: "A reporter as primary witness is useful and biased. Cockrell’s own paper ran the story. Imitators followed. The first night is the file. The seal-skin detail is the part that does not read like a bear.",
    evidence: "Grafton Sentinel coverage, June 1964; later Cockrell interviews. No photograph of the creature.",
    sources: [
      "Grafton Sentinel, 17 June 1964",
      "West Virginia press follow-ups",
    ],
    lat: 39.341,
    lng: -80.019,
    place: "Grafton, West Virginia",
    country: "USA",
    year: 1964,
  },
  {
    id: "dover-demon",
    title: "Dover Demon",
    kicker: "1977",
    subtitle: "Massachusetts · peach-skinned watcher",
    lede: "Three teenagers in three cars described a large-headed, long-fingered figure on a wall and in the road. No one named it a grey until later.",
    summary: "On 21–23 April 1977, Bill Bartlett, John Baxter, and Abby Brabham separately reported a smallish, hairless, large-eyed biped in Dover, Massachusetts. Bartlett’s coloured pencil drawing — melon head, tendril fingers, peach skin — is the icon. Loren Coleman took the case. Skeptics offered a foal or a hoax among friends. The three were not in one car.",
    body: "A three-witness, three-night suburban cluster with a contemporary drawing is better than most creature files. It is still not a capture. The Demon was never seen again in that form, which is either the mark of a one-off animal or of a one-off scare.",
    evidence: "1977 interviews and Bartlett’s drawing as published by Coleman; no photo, no prints cast that night.",
    sources: [
      "Loren Coleman field notes / Mysterious America",
      "Boston-area press, April 1977",
    ],
    lat: 42.246,
    lng: -71.283,
    place: "Dover, Massachusetts",
    country: "USA",
    year: 1977,
  },
  {
    id: "jersey-devil",
    title: "Jersey Devil",
    kicker: "1735 / 1909",
    subtitle: "Pine Barrens, New Jersey · Leeds’ devil",
    lede: "A colonial curse story that briefly became a police-and-paper flap. In January 1909 the pines grew wings.",
    summary: "The Leeds Devil is South Jersey folklore — Mother Leeds’ thirteenth child — until the week of 16–23 January 1909, when tracks, winged sightings, and school closures ran from Burlington to Philadelphia. Police and farmers reported a horse-headed, bat-winged thing. Hoaxers later claimed stamps. The 1909 flap is a documented panic; the colonial birth is a tale.",
    body: "Folklore plus a one-week newspaper storm is the American template for a named monster. The Pine Barrens can hide deer, sandhill cranes, and pranksters. What 1909 proves is not a breeding population. It proves the name was already waiting when the tracks appeared.",
    evidence: "January 1909 Philadelphia and South Jersey papers; school and mill closures as reported. No specimen. 1735 ‘birth’ is folklore.",
    sources: [
      "Philadelphia Evening Bulletin and Inquirer, January 1909",
      "South Jersey historical-society compilations of the 1909 flap",
    ],
    lat: 39.7,
    lng: -74.65,
    place: "Pine Barrens, New Jersey",
    country: "USA",
    year: 1909,
  },
  {
    id: "spring-heeled-jack",
    title: "Spring-heeled Jack",
    kicker: "1837–1838",
    subtitle: "London · leaping attacker",
    lede: "A clawed, helmeted figure who spat blue fire and jumped walls. The Lord Mayor put it on the blotter.",
    summary: "Beginning in late 1837, London and then the Midlands reported a leaping assailant: helmet, cloak, metal claws, sometimes a jet of flame. Jane Alsop’s February 1838 assault in Bow is the detailed case. The Lord Mayor of London received public letters. Penny dreadfuls ate the rest. No arrest stuck. The file is the ancestor of every later winged urban phantom.",
    body: "Victorian panic plus cheap print can mint a devil. Alsop’s statement to police is still the least literary piece. Fire-breathing armour is not a barn owl. Treat Jack as a named cluster of assaults and sightings, not as a species, and not as a fully solved hoax.",
    evidence: "1838 London press; Lord Mayor correspondence as reported; Alsop police statement in contemporary papers. No captured costume.",
    sources: [
      "London newspapers, January–March 1838",
      "Later Home Office / Metropolitan Police historical notes",
    ],
    lat: 51.528,
    lng: -0.018,
    place: "Old Ford, London",
    country: "UK",
    year: 1838,
  },
  {
    id: "chupacabra",
    title: "Chupacabra",
    kicker: "1995",
    subtitle: "Puerto Rico · goatsucker",
    lede: "Livestock drained, a spike-backed biped in Canóvanas. Then the name migrated to Texas and became a mangy coyote.",
    summary: "In 1995, Puerto Rico — especially Canóvanas under Mayor José ‘Chemo’ Soto — reported a wave of livestock deaths and a creature Madelyne Tolentino described with spines and red eyes. The Spanish name stuck. Later mainland ‘chupacabras’ were mostly hairless canids with sarcoptic mange, typed by USDA and university labs. The original island biped was never bagged. The two files are often collapsed; they should not be.",
    body: "A 1995 Caribbean occupant-style creature and a 2000s Texas coyote disease are different exhibits. Conspiracy versions invoke secret labs and failed genetic tests. The lab papers on the canids are real and boring. The Puerto Rican wave still has police and mayor statements and no body.",
    evidence: "1995 Puerto Rican press and municipal statements; later USDA/Texas A&M IDs of mange-coyotes. No 1995 island specimen.",
    sources: [
      "El Nuevo Día and associated 1995 coverage",
      "Texas A&M / USDA comments on mainland carcasses",
    ],
    lat: 18.379,
    lng: -65.905,
    place: "Canóvanas, Puerto Rico",
    country: "USA",
    year: 1995,
  },
  {
    id: "bray-road",
    title: "Beast of Bray Road",
    kicker: "1991",
    subtitle: "Elkhorn, Wisconsin · dogman",
    lede: "A werewolf that would not stay in October. Linda Godfrey wrote down the county.",
    summary: "In 1991 the Walworth County newspaper ran reports — gathered by reporter Linda S. Godfrey — of a large wolf-headed biped along Bray Road near Elkhorn. Witnesses included named locals who had not asked to be in a monster story. Godfrey’s books made ‘dogman’ a Midwestern file. DNR prefers wolf and bear on hind legs. The posture in the better reports is not a stretch-stand.",
    body: "A competent small-town reporter is a useful instrument. Godfrey treated the witnesses as a police blotter, not as a coven. No carcass has been tagged in Walworth County. The file is the modern type-specimen of the American dogman, whether or not the type is an animal.",
    evidence: "The Week (Walworth County) 1991 reporting; Godfrey’s witness list. No body, no state wildlife ID of an unknown canid.",
    sources: [
      "Linda S. Godfrey, The Beast of Bray Road",
      "Walworth County press, 1991",
    ],
    lat: 42.671,
    lng: -88.53,
    place: "Elkhorn, Wisconsin",
    country: "USA",
    year: 1991,
  },
  {
    id: "lizard-man",
    title: "Lizard Man of Scape Ore",
    kicker: "1988",
    subtitle: "Bishopville, South Carolina · scaly biped",
    lede: "Christopher Davis said a green, three-toed thing climbed his car in the swamp. The sheriff opened a folder.",
    summary: "In the summer of 1988, 17-year-old Christopher Davis reported a 7-foot lizard-like biped at Scape Ore Swamp after a puncture-flat. Other Lee County residents reported chewed chrome and three-toed tracks. Sheriff Liston Truesdale took it seriously enough to log. Casts were shown. A later hoaxer claimed some tracks. Davis did not recant the first night.",
    body: "A teenager, a swamp, and a sheriff’s press conference is a complete American cryptid cycle. Subtract the copycats and the first collision remains. No reptile of that size is on the South Carolina list. That is the whole file.",
    evidence: "Lee County sheriff statements, July 1988; local press; disputed casts. No specimen.",
    sources: [
      "The Item (Sumter) and Associated Press, July 1988",
      "Lee County Sheriff’s Office contemporary statements",
    ],
    lat: 34.218,
    lng: -80.249,
    place: "Scape Ore Swamp, South Carolina",
    country: "USA",
    year: 1988,
  },
  {
    id: "loveland-frog",
    title: "Loveland Frog",
    kicker: "1955 / 1972",
    subtitle: "Ohio · police and a riverside biped",
    lede: "A businessman in 1955, then two officers in 1972, described three-foot frog-faced things by the Little Miami.",
    summary: "The Loveland file has two layers: March 1955, when a traveling salesman reported three small bipedal frog-men with a wand of sparks; and March 1972, when officers Ray Shockey and Mark Mathews, on separate nights, reported a large frog-faced animal near the river. Mathews later said he thought it was a large iguana or lizard and had shot at it. The first night has no such walk-back.",
    body: "A police witness who recants toward a known exotic is a gift to the sceptic. It does not automatically close 1955. Keep the two dates stapled and labelled. No body was booked into the Loveland station.",
    evidence: "1955 Cincinnati-area press; 1972 officer interviews and Mathews’ later iguana statement. No specimen.",
    sources: [
      "Cincinnati Post / Enquirer coverage, 1955 and 1972",
      "Later on-record comments by Officer Mark Mathews",
    ],
    lat: 39.269,
    lng: -84.264,
    place: "Loveland, Ohio",
    country: "USA",
    year: 1972,
  },
  {
    id: "kelly-goblins",
    title: "Kelly–Hopkinsville goblins",
    kicker: "1955",
    subtitle: "Christian County, Kentucky · farmhouse siege",
    lede: "Eleven people, rifles, and small glowing-eyed figures at the windows until dawn. The police and Fort Campbell came.",
    summary: "On the night of 21–22 August 1955, the Sutton family and guests at a farmhouse between Kelly and Hopkinsville opened fire on small, large-eared, glowing-eyed creatures that kept coming back to the windows and roof. Hopkinsville police, state troopers, and military police from Fort Campbell found a shot-up house and no bodies. Project Blue Book logged it. This is the American goblin siege, filed as both CE-3 and cryptid.",
    body: "Sober multiple witnesses plus a shot house plus a military police visit is a stronger package than a lone woods story. Tin-hat silhouettes and ‘little green men’ in the press did the rest. No corpse, no captured helmet. The family did not make a career of it.",
    evidence: "Hopkinsville police and newspaper reports, 22 Aug 1955; Blue Book card; later interviews. No recovered entity.",
    sources: [
      "Kentucky New Era, 22 August 1955",
      "Project Blue Book Kelly-Hopkinsville card",
      "Isabel Davis / Ted Bloecher case study",
    ],
    lat: 36.921,
    lng: -87.48,
    place: "Kelly, Kentucky",
    country: "USA",
    year: 1955,
  },
  {
    id: "enfield-horror",
    title: "Enfield Horror",
    kicker: "1973",
    subtitle: "Illinois · three-toed yard thing",
    lede: "Henry Hall said a gray, short-armed, pink-eyed animal attacked on the tracks. A child had a story the same week.",
    summary: "On 25 April 1973 in Enfield, Illinois, Henry McDaniel (often Hall in retellings) reported a gray three-toed creature with short forelimbs at his door, then on the railroad tracks. Sheriff’s deputies took a call. A boy had a separate sighting. Tracks were claimed in the yard. The town name collides with the English poltergeist; they are not the same file.",
    body: "A one-week Illinois panic with a named homeowner and a deputy is small and usable. It never developed a second season. File it as a Midwestern quadruped-biped, not as the English Enfield.",
    evidence: "1973 Illinois press; county sheriff comments. No body.",
    sources: [
      "Illinois papers, April 1973",
      "Fortean compilations of the McDaniel report",
    ],
    lat: 38.098,
    lng: -88.337,
    place: "Enfield, Illinois",
    country: "USA",
    year: 1973,
  },
  {
    id: "thunderbird",
    title: "Thunderbird",
    kicker: "1977",
    subtitle: "Lawndale, Illinois · giant bird",
    lede: "A ten-year-old was lifted off the ground, his mother said, by a bird with a wingspan that did not fit the field guide.",
    summary: "On 25 July 1977 in Lawndale, Illinois, several children and Marlon Lowe’s mother reported two enormous dark birds; one allegedly lifted Marlon a short distance before dropping him. Police logged a giant-bird call. Ornithology offered turkey vulture and heron. The lift is the part that does not fit. Older thunderbird files (Tombstone 1890, Alaska) are weaker paper.",
    body: "A named child, a named street, a police call: that is why Lawndale is the modern thunderbird type. Memory inflates wingspans. It does not always invent a lift. No feather was kept that sequenced as unknown.",
    evidence: "1977 central Illinois press; police log as reported. No specimen, no photo of the birds.",
    sources: [
      "Central Illinois newspapers, July 1977",
      "Later interviews compiled in cryptozoology casebooks",
    ],
    lat: 40.207,
    lng: -90.213,
    place: "Lawndale, Illinois",
    country: "USA",
    year: 1977,
  },
  {
    id: "pope-lick",
    title: "Pope Lick Monster",
    kicker: "1980s–",
    subtitle: "Louisville · goatman on the trestle",
    lede: "A sheep-headed figure beside a Norfolk Southern trestle. The deaths are real. They are from the tracks, not from horns.",
    summary: "Louisville folklore places a goatman at the Pope Lick trestle in Fisherville. Since the 1980s, trespassers have been killed by trains while looking for it. Police and the railroad treat the monster as a lure, not as a suspect. The file on this desk is the lethal urban legend — and the handful of rumoured sightings that keep people climbing.",
    body: "A legend that kills is still a legend. Do not file the fatalities as cryptid predation. File them as the cost of a story that attached itself to a working trestle. Sighting claims remain thin and late.",
    evidence: "Louisville Metro / railroad statements on trespassing deaths; local folklore collections. No biological evidence.",
    sources: [
      "Louisville Courier-Journal coverage of trestle deaths",
      "Norfolk Southern / local police warnings",
    ],
    lat: 38.192,
    lng: -85.575,
    place: "Pope Lick Creek, Kentucky",
    country: "USA",
    year: 1988,
  },
  {
    id: "batsquatch",
    title: "Batsquatch",
    kicker: "1994",
    subtitle: "Mount St. Helens · winged ape",
    lede: "A motorist on a closed mountain road described a purple-tinged, bat-winged sasquatch after the mountain had already blown once.",
    summary: "In 1994, Brian Canfield reported a stall on SR-504 and a wide-winged, blue-tinted primate beside the van near Mount St. Helens. Local radio ran it. The name is later and ugly. The report is a single-witness, high-strangeness mix of hairy hominid and mothman. It never had a second night.",
    body: "One driver, one mountain, one colourful description. Keep it as a satellite of Ape Canyon and Mothman, not as a species. St. Helens already had apes in 1924. Wings are the 1994 addition.",
    evidence: "1994 Washington radio/press interviews with Canfield. No photo, no second witness.",
    sources: [
      "Washington-state radio interviews, 1994",
      "Later cryptozoology summaries",
    ],
    lat: 46.2,
    lng: -122.18,
    place: "Mount St. Helens, Washington",
    country: "USA",
    year: 1994,
  },
  {
    id: "nessie",
    title: "Nessie / Loch Ness Monster",
    kicker: "1933–",
    subtitle: "Scotland · long-necked lake file",
    lede: "A 1933 road-wave and a 1934 ‘surgeon’s photograph’ built the modern Nessie. The photograph was a toy. The sonar contacts are not toys, and not a species.",
    summary: "Modern Nessie begins with the 1933 Spicer roadside sighting and the Daily Mail’s hunt. The April 1934 Surgeon’s Photograph, credited to Robert Kenneth Wilson, ran worldwide; in 1994 Christian Spurling said it was a toy submarine. Dinsdale’s 1960 film, Operation Deepscan in 1987, and later eDNA under Prof. Neil Gemmell (2018) found eel DNA and no unknown reptile. The loch is deep, long, and still producing wake reports.",
    body: "A confessed hoax photograph does not retire a lake. It does retire that photograph. The honest remainder is wakes, sonar anomalies, and an ecosystem that can feed large eels. A plesiosaur population is not in the eDNA. The tourist board does not get a vote.",
    evidence: "1933–34 press; Spurling confession (1994); Dinsdale film as an object; Deepscan logs; Gemmell eDNA preprint/report. No carcass.",
    sources: [
      "Inverness Courier, 1933",
      "Surgeon’s Photograph, Daily Mail, 21 April 1934",
      "Gemmell et al., Loch Ness eDNA survey, 2019",
    ],
    lat: 57.323,
    lng: -4.424,
    place: "Loch Ness, Scotland",
    country: "UK",
    year: 1933,
  },
  {
    id: "champ",
    title: "Champ",
    kicker: "1883 / 1977",
    subtitle: "Lake Champlain · Mansi photograph",
    lede: "A lake older than the states that share it. The 1977 Mansi photo is the exhibit. The captain’s log from 1609 is not a serpent.",
    summary: "Champ is the Lake Champlain long-necked file. Samuel de Champlain did not describe the modern monster; 19th-century papers did. On 5 July 1977 Sandra Mansi photographed a dark hump and neck in the lake; the negative was lost, the print survived. Later sonar and the 1981 ‘Champ legislation’ in New York/Vermont are real paper. Identification is not.",
    body: "A colour print without a negative is a wounded artifact, not a worthless one. Boat wakes and sturgeon do honest work here. So does a large lake with a long vernacular. No body has come ashore in a lab.",
    evidence: "Mansi print (1977); 19th-c newspaper notices; NY/VT protective resolutions. Negative missing. No specimen.",
    sources: [
      "Sandra Mansi photograph, 5 July 1977",
      "New York and Vermont Champ resolutions, 1981–82",
      "Champlain lake-monster press corpus",
    ],
    lat: 44.532,
    lng: -73.328,
    place: "Lake Champlain",
    country: "USA",
    year: 1977,
  },
  {
    id: "ogopogo",
    title: "Ogopogo",
    kicker: "1926–",
    subtitle: "Okanagan Lake, British Columbia · N’ha-a-itk",
    lede: "A nsyilxcən lake being that English vaudeville renamed. The sacred file and the tourist file are not the same animal.",
    summary: "N’ha-a-itk is an Okanagan/syilx lake being with ritual and geographic rules. ‘Ogopogo’ is a 1920s music-hall name stuck onto a string of humps in Okanagan Lake. 20th-century photographs and home movies show wakes. First Nations testimony is not a cryptozoology checklist and should not be flattened into one.",
    body: "Treat the syilx tradition as culture, not as a poorly shot plesiosaur. Treat the 20th-century tourist sightings as a separate, weaker natural-history file. Folding them together is the usual mistake.",
    evidence: "syilx oral history as published with permission in ethnographic literature; 1926-onward settler press and film. No specimen.",
    sources: [
      "syilx / Okanagan ethnographic accounts of N’ha-a-itk",
      "Kelowna and Vernon press, 1920s–",
    ],
    lat: 49.862,
    lng: -119.48,
    place: "Okanagan Lake, British Columbia",
    country: "Canada",
    year: 1926,
  },
  {
    id: "cadborosaurus",
    title: "Cadborosaurus",
    kicker: "1933",
    subtitle: "Cadboro Bay, British Columbia · ‘Caddy’",
    lede: "A horse-headed sea serpent in the Strait of Juan de Fuca the same year Nessie went global. Carcasses kept arriving and turning into sharks.",
    summary: "In 1933 Victoria newspapers named Cadborosaurus after repeated sightings of a long-necked marine animal in Cadboro Bay. Later West Coast carcasses — Naden Harbour 1937 among them — were photographed and then lost or re-identified. Lehn and Bousfield argued for an unknown pinniped-like form. Fisheries did not.",
    body: "A coastal serpent file lives or dies on carcasses. This one has had several, and the ones that reached a lab became known sharks or decay artifacts. The living sightings remain a Pacific Northwest maritime unexplained, not a species description.",
    evidence: "Victoria Daily Times 1933 coverage; Naden Harbour carcass photographs; later identifications as basking shark / decay. No accepted holotype.",
    sources: [
      "Victoria Daily Times, 1933",
      "Lehn & Bousfield papers on Cadborosaurus",
      "Fisheries/museum comments on carcasses",
    ],
    lat: 48.455,
    lng: -123.293,
    place: "Cadboro Bay, Victoria",
    country: "Canada",
    year: 1933,
  },
  {
    id: "yeti",
    title: "Yeti",
    kicker: "1921–",
    subtitle: "Himalaya · metch kangmi / ‘abominable snowman’",
    lede: "A Sherpa and Tibetan file that the 1921 Everest reconnaissance turned into an Empire headline. The 1951 Shipton print is the icon.",
    summary: "Howard-Bury’s 1921 reconnaissance reported metch kangmi — ‘filthy snowman’ — later mistranslated ‘abominable.’ Eric Shipton’s 1951 photograph of a large print beside an ice axe became the Western type image. Hillary’s 1960 hunt found no animal. Hair and fecal samples usually return bear, cow, or human. The 2017 Chinese/Tibet reserve language and old Soviet ‘snowman commissions’ show states took it seriously enough to look.",
    body: "A mistranslation plus a good photograph built a global cryptid out of a regional being (yet-teh, migoi, dzu-teh — not one animal in the source languages). Brown bear and Tibetan blue bear explain many prints. They do not automatically explain every 1950s high-camp report. No skin has been sequenced as unknown primate in a replicable paper.",
    evidence: "Shipton 1951 photograph; 1921 expedition narrative; Hillary 1960; various hair papers returning Ursus. No holotype.",
    sources: [
      "C.K. Howard-Bury, Mount Everest: The Reconnaissance, 1921",
      "Eric Shipton Menlung Glacier print, 1951",
      "Hillary–Shipton 1960 search reporting",
    ],
    lat: 27.988,
    lng: 86.925,
    place: "Menlung Glacier / Everest region",
    country: "Nepal",
    year: 1951,
  },
  {
    id: "orang-pendek",
    title: "Orang Pendek",
    kicker: "1920s–",
    subtitle: "Kerinci, Sumatra · short forest person",
    lede: "A small, stocky biped in a real national park. Rangers and a long-term Western fieldworker kept taking it seriously.",
    summary: "Orang pendek (‘short person’) is a Sumatran biped reported from Kerinci Seblat: ground-dwelling, powerful shoulders, not an orangutan. Colonial planters wrote it down; park staff still do. Debbie Martyr’s 1990s–2000s fieldwork produced casts and hair that did not close the species. A surviving small hominid on Sumatra is biogeographically less absurd than a giant in Washington. It is still uncaught.",
    body: "This is one of the few cryptid files where professional fieldworkers treated the reports as a survey problem, not a carnival. That raises the quality of the paper. It does not put a skull in Bogor.",
    evidence: "Colonial gazetteers; Kerinci Seblat ranger reports; Martyr expedition notes and casts. No voucher specimen.",
    sources: [
      "Debbie Martyr / Fauna & Flora International Kerinci reports",
      "Sumatran colonial and park-service notices",
    ],
    lat: -2.4,
    lng: 101.5,
    place: "Kerinci Seblat, Sumatra",
    country: "Indonesia",
    year: 1995,
  },
  {
    id: "almasty",
    title: "Almasty",
    kicker: "1950s–",
    subtitle: "Caucasus · wildman",
    lede: "A relic hominid in the Caucasus and Pamir, taken seriously by some Soviet field teams, never tabled as a bone.",
    summary: "Almasty (and related kabard / kaptar names) is the Caucasus wildman file. Marie-Jeanne Koffmann, a surgeon, collected hundreds of interviews. Soviet ‘snowman commissions’ after 1958 looked and did not find. The reports describe a more human, less ape-like figure than Bigfoot. No grave was opened under a pathologist.",
    body: "Interview volume is not a skeleton. Koffmann’s corpus is the best paper on this desk for the western steppe-and-ridge wildman. It remains folklore-plus until a bone.",
    evidence: "Koffmann interview archive as published; 1958–59 Soviet Academy interest. No specimen.",
    sources: [
      "Marie-Jeanne Koffmann Caucasus interview corpus",
      "Soviet Academy of Sciences snowman commission notices, late 1950s",
    ],
    lat: 43.48,
    lng: 43.6,
    place: "Kabardino-Balkaria",
    country: "Russia",
    year: 1958,
  },
  {
    id: "yowie",
    title: "Yowie",
    kicker: "1870s / 1970s",
    subtitle: "Australia · hairy bushman",
    lede: "Settler papers used Yahoo and yowie for a hairy bush figure. The 1970s made it a national cryptid. Aboriginal beings with other names are not automatically the same file.",
    summary: "Nineteenth-century Australian papers used Yahoo/yowie for large hairy bush figures, especially in New South Wales and Queensland. A 1970s boom, Rex Gilroy’s cataloguing, and later Gold Coast-area reports created the modern animal. Distinct Aboriginal beings should not be collapsed into one primate without the communities saying so. No body has been tabled at a museum.",
    body: "Colonial newspapers are primary for the settler creature. They are not authority on Indigenous cosmology. Keep two shelves: the 19th-c Yahoo as a natural-history rumour, and living cultural beings that are not ours to rebrand.",
    evidence: "19th-c Australian newspaper corpus; 1970s–80s reported sightings. No specimen.",
    sources: [
      "Trove / colonial newspaper Yahoo and yowie notices",
      "Rex Gilroy catalogues as secondary compilation",
    ],
    lat: -28.64,
    lng: 153.28,
    place: "Northern New South Wales",
    country: "Australia",
    year: 1876,
  },
  {
    id: "mapinguari",
    title: "Mapinguari",
    kicker: "1990s",
    subtitle: "Amazonia · sloth-footed roarer",
    lede: "A one-eyed, backward-footed forest being in Amazonian testimony. David Oren wondered if a giant sloth had not quite gone.",
    summary: "Mapinguari (and close names) appears in Amazonian Indigenous and caboclo testimony as a roaring, foul, sometimes backward-footed forest creature. Biologist David C. Oren floated a surviving giant ground sloth in the 1990s and collected interviews. No megafaunal bone of Holocene age has been produced from those hunts. Folklore here is older and denser than the zoological wager.",
    body: "Do not reduce a living Amazonian being to a cryptozoologist’s sloth. File Oren’s hypothesis as a scientific overlay. File the testimony as ethnography. Neither shelf currently holds a hide.",
    evidence: "Oren interviews and papers; ethnographic literature. No Holocene Megatherium carcass from the search areas.",
    sources: [
      "David C. Oren papers and interviews, 1990s",
      "Amazonian ethnographic accounts of mapinguari",
    ],
    lat: -5.2,
    lng: -60.0,
    place: "Amazonas",
    country: "Brazil",
    year: 1994,
  },
  {
    id: "mokele-mbembe",
    title: "Mokele-mbembe",
    kicker: "1913–",
    subtitle: "Likouala, Congo Basin · river monster",
    lede: "A long-necked water animal in a swamp the size of a country. Expeditions kept coming back with interviews, not a hide.",
    summary: "Mokele-mbembe (‘one who stops the flow of rivers’) is a Likouala/Congo Basin water-monster file that 20th-century missionaries and later American expeditions cast as a surviving sauropod. Captain Freiherr von Stein zu Lausnitz wrote an early notice (c. 1913). Mackal, Nugent, and others ran expensive, thin surveys. Living sauropods in a fished, paddled watershed would be noisy. Interviews persist.",
    body: "Colonial and evangelical collectors heard a name and reached for dinosaurs. That translation is the conspiracy-adjacent move: Western taxonomy over local water spirits and large known mammals. Keep the river reports. Drop the Jurassic certainty.",
    evidence: "von Stein notice; 1980s Mackal-era expedition write-ups; no photograph that survives scrutiny, no bone.",
    sources: [
      "von Stein zu Lausnitz Likouala notice (as later published)",
      "Roy Mackal, A Living Dinosaur?",
      "Later Congo Basin expedition reports",
    ],
    lat: 1.0,
    lng: 17.6,
    place: "Likouala, Republic of the Congo",
    country: "Republic of the Congo",
    year: 1913,
  },
  {
    id: "kongamato",
    title: "Kongamato",
    kicker: "1923",
    subtitle: "Zambezi / Jiundu · ‘breaker of boats’",
    lede: "Frank Melland printed a Kaonde warning: a flying thing that splits canoes. Later readers drew a pterosaur. The witnesses had not.",
    summary: "In 1923 magistrate Frank H. Melland published Kaonde testimony from the Jiundu swamps of a flying red creature, kongamato, that attacked boats. 1950s newspapers added a ‘pterodactyl’ gloss after a hospital patient supposedly identified a textbook drawing. Large storks and hammerkops live there. A living pterosaur does not, on any bone bed.",
    body: "The 1923 text is ethnography. The pterosaur is a later Western stencil. File Melland. Do not file a Cretaceous survival without a bone.",
    evidence: "Melland, In Witch-Bound Africa (1923); 1950s press pterosaur claims. No specimen.",
    sources: [
      "Frank H. Melland, In Witch-Bound Africa",
      "1950s Northern Rhodesia press follow-ups",
    ],
    lat: -12.2,
    lng: 25.4,
    place: "Jiundu swamps, Zambia",
    country: "Zambia",
    year: 1923,
  },
  {
    id: "mongolian-death-worm",
    title: "Mongolian death worm",
    kicker: "1926–",
    subtitle: "Gobi · olgoi-khorkhoi",
    lede: "A sausage-thick sand worm that kills at a distance. Andrews heard the name. He never bottled one.",
    summary: "Olgoi-khorkhoi — the intestine-worm — is a Gobi folk hazard: thick, red, sometimes electrical or venomous at a distance. Roy Chapman Andrews mentioned it in the 1920s. Czech and later Western expeditions in the 1990s–2000s found sand and stories. No worm of that scale is in the Mongolian Academy’s collections from those hunts.",
    body: "A desert people naming a killer in the dunes is data. A yellow-press ‘death worm’ with lightning is a poster. Keep the Mongolian name and the empty jar.",
    evidence: "Andrews’ popular mentions; later expedition write-ups. No specimen, no photograph in situ that holds up.",
    sources: [
      "Roy Chapman Andrews, On the Trail of Ancient Man (and later popular books)",
      "1990s–2000s Czech/Mongolian search reports",
    ],
    lat: 43.7,
    lng: 104.0,
    place: "Gobi Desert",
    country: "Mongolia",
    year: 1926,
  },
  {
    id: "minhocao",
    title: "Minhocão",
    kicker: "1847–",
    subtitle: "Brazil · giant earth-worm",
    lede: "Nineteenth-century Brazilian papers described a huge burrowing worm that toppled trees and opened trenches. Then the trenches stopped being news.",
    summary: "From the 1840s, Brazilian and European journals (including a notable 1878 notice) described the minhocão: a gigantic worm or armored burrower in Paraná and Mato Grosso that left trench-like tracks and killed cattle. Later zoologists offered giant lungfish, anacondas, or exaggeration. No animal of that diameter was tabled.",
    body: "A 19th-c engineering-scale burrow in a wet interior is interesting even if the animal was a known large vertebrate plus panic. The file is closed as a species, open as a historical anomaly cluster.",
    evidence: "19th-c Brazilian and European natural-history notices. No specimen.",
    sources: [
      "19th-century Brazilian provincial papers",
      "Antonio da Silva / later zoological summaries of minhocão reports",
    ],
    lat: -20.5,
    lng: -54.6,
    place: "Mato Grosso do Sul",
    country: "Brazil",
    year: 1878,
  },
  {
    id: "bunyip",
    title: "Bunyip",
    kicker: "1845–",
    subtitle: "Australian wetlands · water being",
    lede: "A word from across Aboriginal languages, flattened by settlers into one swamp monster. The 1846 skull was a horse.",
    summary: "Bunyip is a settler catch-all for dangerous wetland beings in Aboriginal Australia. 1840s Geelong and Murray reports, a 1846 ‘skull’ displayed in Sydney (horse), and later cattle-killing rumours built a colonial cryptid. Living traditions are multiple, local, and not a single seal-dog. The colonial hunt never produced an unknown mammal.",
    body: "Do not file fifty water-beings as one zoo animal. The colonial papers are useful as a record of settler panic. They are not a field guide. The horse skull is a caution against trophy science.",
    evidence: "1840s Port Phillip / Sydney press; 1846 skull exhibition and later horse ID. No unknown type specimen.",
    sources: [
      "Geelong Advertiser and Sydney press, 1845–47",
      "Later Aboriginal studies cautioning against a single bunyip",
    ],
    lat: -38.15,
    lng: 144.36,
    place: "Geelong / Barwon, Victoria",
    country: "Australia",
    year: 1846,
  },
  {
    id: "beast-gevaudan",
    title: "Beast of Gévaudan",
    kicker: "1764–1767",
    subtitle: "Margeride, France · royal hunt",
    lede: "A man-eater that forced Louis XV to send troops. Wolves were killed. The count of the dead is not in dispute. The animal’s identity still is.",
    summary: "From 1764 to 1767 the Margeride in the former Gévaudan was terrorized by an animal or animals that killed scores of people, many of them women and children. Royal wolvers, dragoons, and finally Jean Chastel are in the administrative paper. A large wolf was shown to the court. Descriptions (reddish coat, black stripe, blunt snout) never sat easily on an ordinary wolf, which is why the file still opens.",
    body: "This is not a tabloid cryptid. It is a documented rural massacre with intendants’ letters. Hyena, wolfdog, and serial wolf are the modern bets. A unique predator is the romantic one. The conspiracy is later and thin; the death toll is not.",
    evidence: "French royal and provincial correspondence; burial and bounty records. The mounted animal sent to Versailles is lost. No DNA.",
    sources: [
      "Intendants’ correspondence, Gévaudan 1764–67",
      "Royal hunt orders under Louis XV",
      "Later forensic-historical tallies of victims",
    ],
    lat: 44.84,
    lng: 3.45,
    place: "Saugues / Margeride",
    country: "France",
    year: 1764,
  },
  {
    id: "beast-bodmin",
    title: "Beast of Bodmin",
    kicker: "1983–",
    subtitle: "Cornwall · big cat",
    lede: "Livestock kills and a black panther on the moor. MAFF measured a skull and said no. Farmers kept seeing a cat.",
    summary: "From the early 1980s, Bodmin Moor produced repeated reports of a large melanistic felid and mutilated sheep. In 1995 the Ministry of Agriculture published a report: no verifiable big cat. A later skull found in the river was a leopard, but imported as a pelt/rug, not a Cornish resident. Escapee pumas from 1970s UK law changes remain the ordinary bet.",
    body: "Britain’s alien-big-cat file is a post-Dangerous Wild Animals Act story: released pets plus sheep plus cameras that always miss the face. Bodmin is the type case because the ministry bothered to write it down. The paper says no. The hill farmers did not all recant.",
    evidence: "MAFF 1995 report; 1995 skull ID as imported leopard; ongoing farmer reports. No wild breeding population proven.",
    sources: [
      "MAFF, The Evidence for the Presence of Large Exotic Cats (1995)",
      "Cornwall press ABC reports, 1980s–",
    ],
    lat: 50.545,
    lng: -4.613,
    place: "Bodmin Moor, Cornwall",
    country: "UK",
    year: 1995,
  },
  {
    id: "montauk-monster",
    title: "Montauk Monster",
    kicker: "2008",
    subtitle: "Long Island · washed-up carcass",
    lede: "A hairless, beak-faced body on the sand went around the world in a week. The lab story is a raccoon. The town name did the rest.",
    summary: "In July 2008 a decayed carcass photographed at Ditch Plains, Montauk, was billed as a mystery monster. William Fox and later commentators identified raccoon. The coincidence of the name with the Montauk Project file is why it sits on this desk at all. It is a lesson in how a beach and a legend share a zip code.",
    body: "Do not promote a raccoon into a bioweapon because Camp Hero is up the road. Do file the speed with which a carcass became proof of the underground. That speed is the phenomenon.",
    evidence: "July 2008 photographs; wildlife IDs as raccoon. No chain-of-custody tissue that sequenced otherwise.",
    sources: [
      "Local and wire photographs, July 2008",
      "Published raccoon-decay identifications",
    ],
    lat: 41.039,
    lng: -71.904,
    place: "Montauk, New York",
    country: "USA",
    year: 2008,
  },
  {
    id: "zuiyo-maru",
    title: "Zuiyō-maru carcass",
    kicker: "1977",
    subtitle: "Off New Zealand · trawled ‘plesiosaur’",
    lede: "A Japanese trawler hauled a rotting sea animal with flippers and a long neck. The crew dumped it. The photographs went around the world.",
    summary: "On 25 April 1977 the trawler Zuiyō-maru brought up a 10-metre decaying carcass east of New Zealand. The crew photographed, measured, took samples, and threw it back for the smell. Papers called it a plesiosaur. Later tissue analysis (Prof. Ibe and others) matched basking shark, whose decayed gill-rakers fake a neck. The photographs remain impressive. The chemistry is shark.",
    body: "This is the textbook globster: a real haul, a real photograph, a real misread of decay. Keep it next to Nessie as a caution, not as a surviving reptile.",
    evidence: "Crew photographs and measurements, 1977; subsequent amino-acid / tissue work consistent with Cetorhinus maximus.",
    sources: [
      "1977 Japanese press photographs of the Zuiyō-maru carcass",
      "Ibe et al. tissue analyses as published",
    ],
    lat: -39.3,
    lng: 173.5,
    place: "East of New Zealand",
    country: "New Zealand",
    year: 1977,
  },
  {
    id: "michigan-dogman",
    title: "Michigan Dogman",
    kicker: "1887 / 1987",
    subtitle: "Wexford County · bipedal wolf",
    lede: "A 1987 radio song put a 19th-century lumber-camp story on the map. Northwoods reports did not all start as a joke.",
    summary: "Steve Cook’s April 1987 WTCM song ‘The Legend’ retold a Wexford County tale of a seven-foot dog-headed biped seen by lumberjacks in 1887, then by later hunters around Paris and Reed City. Callers answered with their own nights. Skeptics file the whole thing as an April Fool that escaped. The song is real. So is a cluster of independent-looking reports that used the same silhouette before the chorus was famous — and a larger cluster that used it after.",
    body: "A novelty record can mint a monster. It can also give a name to something people were already telling sheriffs. Bray Road is the Wisconsin cousin; this is the Michigan one. No carcass. No collar.",
    evidence: "WTCM broadcast and later Cook interviews; scattered northern-Michigan press. No specimen, no authenticated 1887 primary.",
    sources: [
      "Steve Cook, The Legend (WTCM-FM, Traverse City, 1987)",
      "Wexford / Osceola county press retrospectives",
    ],
    lat: 44.27,
    lng: -85.58,
    place: "Wexford County, Michigan",
    country: "USA",
    year: 1987,
  },
  {
    id: "momo",
    title: "Momo / Missouri Monster",
    kicker: "1972",
    subtitle: "Louisiana, Missouri · pumpkin-headed biped",
    lede: "Three children on a bluff described a hairy figure with a head like a pumpkin and hair over the eyes. Police and a MUFON investigator took the night seriously.",
    summary: "On 11 July 1972, Terry Harrison and two other children near Louisiana, Missouri, reported a large, three-toed, pumpkin-headed biped by the family home on a Mississippi bluff. Neighbors reported a stench and animal deaths. Ted Phillips investigated. The town named it Momo. Footprint casts and a brief regional flap followed. No body.",
    body: "A three-child first sighting is a weak holotype and a strong local panic. Phillips’ notes are why the file is better than a mascot. Hair over the eyes is the diagnostic that does not read like a bear on its hind legs — or it is the diagnostic of a story that settled too fast.",
    evidence: "1972 Louisiana Press-Journal and associated wires; Phillips field notes as later published. Casts without a matching animal.",
    sources: [
      "Louisiana Press-Journal, July 1972",
      "Ted Phillips / MUFON case write-ups",
    ],
    lat: 39.449,
    lng: -91.052,
    place: "Louisiana, Missouri",
    country: "USA",
    year: 1972,
  },
  {
    id: "grassman",
    title: "Ohio Grassman",
    kicker: "1978",
    subtitle: "Minerva · family of bipeds in the grass",
    lede: "The Cayton family said more than one long-haired figure was living in a field behind the house. Minerva became Ohio’s Sasquatch parish.",
    summary: "In August 1978, Mary Cayton and her sons in Minerva, Ohio, reported a family of large, dark, hairy bipeds using a grass nest in an adjacent field. Neighbors and later Salt Fork State Park reports fed the ‘Grassman’ name. Local police logged some calls. No kill, no trap, no type specimen from Stark County.",
    body: "A nest in a field is easier to check than a Cascades drainage. That is the problem for the file. Searchers found flattened grass and a story that would not sit down. Ohio still produces annual reports. Annual reports are not a skull.",
    evidence: "1978 Minerva / Alliance press; later Salt Fork compilations. No voucher specimen.",
    sources: [
      "Alliance Review and associated Ohio press, August 1978",
      "Later Salt Fork State Park sighting compilations",
    ],
    lat: 40.73,
    lng: -81.073,
    place: "Minerva, Ohio",
    country: "USA",
    year: 1978,
  },
  {
    id: "mud-monster",
    title: "Murphysboro Mud Monster",
    kicker: "1973",
    subtitle: "Illinois · river-mud biped",
    lede: "A couple on a riverbank, then a police officer, described a muddy white-haired figure. The department wrote it down.",
    summary: "On 25 June 1973, Randy Needham and Cheryl Ray reported a large, light-haired, mud-caked biped along the Big Muddy in Murphysboro, Illinois. Officers who responded described a smell and, in one case, a figure. The police log is why this is not only a campfire story. Searches found impressions. They did not find an animal.",
    body: "A municipal police report is the rare paper in an American monster file. Treat it as a record of what was said that night, not as a species description. Imitators and a later festival are the cultural aftertaste.",
    evidence: "Murphysboro police reports as quoted in 1973 press; no photograph of the figure, no bones.",
    sources: [
      "Murphysboro and southern Illinois press, June 1973",
      "Police-log quotations in contemporaneous coverage",
    ],
    lat: 37.764,
    lng: -89.335,
    place: "Murphysboro, Illinois",
    country: "USA",
    year: 1973,
  },
  {
    id: "minnesota-iceman",
    title: "Minnesota Iceman",
    kicker: "1968",
    subtitle: "Rollingstone · carnival carcass in ice",
    lede: "Heuvelmans and Sanderson said they had seen a frozen hominid in a Midwestern sideshow. Hansen said the original went back into storage. What toured was, by his later word, a copy.",
    summary: "In December 1968 Bernard Heuvelmans and Ivan T. Sanderson examined a hairy male body in a block of ice exhibited by Frank Hansen. Heuvelmans published it as Homo pongoides. The FBI was asked whether it was a human corpse. Hansen later claimed the original had been withdrawn and a fabricated stand-in was on the road. No laboratory ever sequenced the ice.",
    body: "A possible type specimen that was never allowed out of the freezer is the cruelest kind of cryptid evidence: almost a body, then a showman. Either Hansen had a corpse he could not legally possess, or he had a latex man and two of the century’s better-known zoological writers. The file is that fork. It is not a wild Minnesota primate.",
    evidence: "Heuvelmans 1969 paper; Sanderson’s notes and photos through glass; Hansen interviews. No chain-of-custody tissue.",
    sources: [
      "Bernard Heuvelmans, Note préliminaire sur un spécimen conservé dans la glace (1969)",
      "Ivan T. Sanderson contemporary notes",
      "Frank Hansen public statements",
    ],
    lat: 44.101,
    lng: -91.817,
    place: "Rollingstone, Minnesota",
    country: "USA",
    year: 1968,
  },
  {
    id: "skinwalker-ranch",
    title: "Skinwalker Ranch",
    kicker: "1994–",
    subtitle: "Uintah Basin, Utah · NIDS / BAASS test bed",
    lede: "A cattle ranch that ate a National Institute for Discovery Science budget, then a DIA program. The Ute name was borrowed. The paper is American.",
    summary: "The Sherman family reported cattle mutilations, lights, and wolf-like animals on a Uintah County ranch in the mid-1990s. Robert Bigelow’s NIDS bought the property in 1996. BAASS under AAWSAP later used it as a living laboratory. Skinwalkers at the Pentagon is the memoir. Ute tradition of a skin-walker is a separate, living religious category; this file is the leased ranch and the defense-adjacent study, not that tradition.",
    body: "A ranch with a reality-TV afterlife is easy to sneer at. The NIDS years and the AAWSAP contract are not TV. What is missing is a public instrumented event that survives outside the memoir. File it as the American cryptid/UAP hinge: wolves, orbs, poltergeist, and a Pentagon program in one fence line.",
    evidence: "NIDS purchase and later BAASS work as described in Kelleher/Knapp/Lacatski. No released sensor take that identifies an animal or a craft.",
    sources: [
      "Kelleher & Knapp, Hunt for the Skinwalker (2005)",
      "Lacatski, Kelleher & Knapp, Skinwalkers at the Pentagon",
      "AAWSAP / BAASS contracting as later described in Senate and press",
    ],
    lat: 40.258,
    lng: -109.888,
    place: "Uintah County, Utah",
    country: "USA",
    year: 1996,
  },
  {
    id: "goatman",
    title: "Goatman of Prince George’s County",
    kicker: "1971",
    subtitle: "Maryland · axe-wielding hybrid",
    lede: "University of Maryland folklore plus a 1971 Fletchertown Road panic. A dog was killed. A satyr did not walk into a lab.",
    summary: "In 1971, residents around Bowie and Fletchertown Road reported a hairy, goat-legged or goat-headed figure, sometimes with an axe. A badly injured dog (owned by the Pumphrey family in some tellings) fed the wires. Campus folklore at College Park already had a Goatman — an escaped USDA experiment in the popular version. Police treated calls as vandalism and nerves. The hybrid stuck.",
    body: "Folklore that eats a police blotter is still folklore. The file is the 1971 cluster and the lab-escape story that rode with it, not a faun in the park. Pope Lick is the Kentucky cousin with a body count attached to the trestle, not to the goat.",
    evidence: "Prince George’s County press, 1971; University of Maryland folklore collections. No specimen.",
    sources: [
      "Prince George’s County and Washington-area press, 1971",
      "University of Maryland campus folklore compilations",
    ],
    lat: 38.964,
    lng: -76.779,
    place: "Bowie, Maryland",
    country: "USA",
    year: 1971,
  },
  {
    id: "snallygaster",
    title: "Snallygaster",
    kicker: "1909",
    subtitle: "Frederick County, Maryland · bird-reptile flap",
    lede: "The Middletown Valley Register ran a flying monster in the same winter the Jersey Devil walked. A German settler word did the rest.",
    summary: "In February 1909 the Middletown Valley Register and other Frederick County papers described a winged, half-bird half-reptile predator — the snallygaster, from Pennsylvania German schnelle geeschter (‘quick spirits’). Sightings and egg stories spread through the valley. The Bureau of Prohibition later used the name as colour. No skin was tanned in Frederick.",
    body: "A newspaper monster in the same month as the 1909 Jersey Devil flap is either copycat journalism or a regional winged-thing season. Keep both files. Believe neither on paper alone.",
    evidence: "1909 Middletown Valley Register and Maryland valley press. No specimen, no photograph.",
    sources: [
      "Middletown Valley Register, February 1909",
      "Frederick County historical-society retrospectives",
    ],
    lat: 39.444,
    lng: -77.545,
    place: "Middletown, Maryland",
    country: "USA",
    year: 1909,
  },
  {
    id: "dark-watchers",
    title: "Dark Watchers",
    kicker: "1938",
    subtitle: "Santa Lucia Range · silhouettes on the ridge",
    lede: "Steinbeck put them in a story. Spanish-speaking ranchers already had los Vigilantes Oscuros. The ridge still grows figures at dusk.",
    summary: "Along the Santa Lucia Mountains of Big Sur, travelers have described tall, hat-and-cloak silhouettes on ridgelines that vanish when approached. John Steinbeck used them in the 1938 story ‘Flight.’ Robinson Jeffers knew the same hills. Hispanic ranching lore called them the Dark Watchers. No photograph holds one. No ranger has booked one.",
    body: "Backlit hikers, heat shimmer, and a literary brand explain most of it. They do not explain why the same silhouette — hat, staff, no face — recurs in independent tellings. File it as a coastal earthlight/figure cluster, not as a species.",
    evidence: "Steinbeck 1938; Jeffers’ coast poems; ranching oral history as later collected. No instrumented capture.",
    sources: [
      "John Steinbeck, Flight (The Long Valley, 1938)",
      "Robinson Jeffers, coastal poems set on the Santa Lucias",
      "Later Big Sur oral-history collections",
    ],
    lat: 36.25,
    lng: -121.78,
    place: "Santa Lucia Range, California",
    country: "USA",
    year: 1938,
  },
  {
    id: "tahoe-tessie",
    title: "Tahoe Tessie",
    kicker: "1984",
    subtitle: "Lake Tahoe · deep-water animal",
    lede: "Washoe water-being stories plus a 1980s tourist cryptid. The lake is deep enough. The photographs are not.",
    summary: "Lake Tahoe’s deep, cold basin has long had Washoe traditions of a water being. The modern ‘Tessie’ brand — humps, a dark back, a 1984 research-group push — is a Nessie export. Sonar hits and tourist snaps circulate. No carcass has come ashore that was not a known fish or a log.",
    body: "A 1,600-foot lake can hide a sturgeon story. It has not produced a plesiosaur. Keep Tessie with Champ and Ogopogo as the western-American lake file, not as a separate biology.",
    evidence: "1980s Tahoe press and later tourist photographs. No voucher specimen.",
    sources: [
      "Tahoe-area press, 1980s Tessie coverage",
      "Washoe traditional water-being accounts as later published",
    ],
    lat: 39.09,
    lng: -120.03,
    place: "Lake Tahoe",
    country: "USA",
    year: 1984,
  },
  {
    id: "chessie",
    title: "Chessie",
    kicker: "1982",
    subtitle: "Chesapeake Bay · Love Point videotape",
    lede: "A Maryland couple taped a long dark animal off Kent Island. The Navy looked. The Bay kept its seal explanation and its mascot.",
    summary: "On 31 May 1982 Robert and Karen Frew videotaped a long, dark, undulating animal from Love Point on Kent Island. Earlier 1978 sightings had already named it Chessie. The tape was shown to scientists and, in some retellings, to Navy reviewers. Manatee, seal, and eel are the ordinary bets. A resident unknown vertebrate is the extraordinary one. The Bay is trawled.",
    body: "A videotape is better than a hump story. It is still not a body. File Chessie as the Mid-Atlantic lake-monster that happens to live in salt water.",
    evidence: "1982 Frew videotape as screened; Chesapeake press. No specimen.",
    sources: [
      "Maryland and wire coverage of the 31 May 1982 Love Point tape",
      "Earlier 1978 Chesapeake ‘Chessie’ reports",
    ],
    lat: 39.03,
    lng: -76.3,
    place: "Love Point, Kent Island, Maryland",
    country: "USA",
    year: 1982,
  },
  {
    id: "altamaha-ha",
    title: "Altamaha-ha",
    kicker: "1981",
    subtitle: "Georgia coast · river serpent",
    lede: "A long-bodied animal in the Altamaha from Darien to the sound. Shrimp boats would have caught a breeding population. They have not.",
    summary: "From the 1960s through the 1980s, and in later spikes, people along the Altamaha River near Darien, Georgia, reported a sturgeon-sized, humped, sometimes seal-headed animal — Altamaha-ha, or Altie. A 1981 cluster made the regional papers. Atlantic sturgeon already live in that river. That is the leading ID. It does not automatically cover every ‘too long, too fast’ report.",
    body: "A named river monster on a working waterway is a high bar. Georgia’s coast is not Loch Ness. File the sturgeon, file the leftover reports, do not invent a new reptile for the chamber of commerce.",
    evidence: "Coastal Georgia press, especially early-1980s; no carcass identified as unknown.",
    sources: [
      "Darien / Brunswick press, 1981 cluster",
      "Later Georgia DNR sturgeon comments",
    ],
    lat: 31.37,
    lng: -81.434,
    place: "Darien, Georgia",
    country: "USA",
    year: 1981,
  },
  {
    id: "thetis-lake",
    title: "Thetis Lake monster",
    kicker: "1972",
    subtitle: "Victoria, B.C. · gill-man",
    lede: "Two teenagers, a police report, and a second pair of witnesses the next day. A Creature from the Black Lagoon costume is the tidy close. The blotter is still in the file.",
    summary: "On 19 August 1972, Gordon Pike and Robin Flewellyn told Victoria police a silver, scaly, gilled humanoid had slashed one of them at Thetis Lake. On 20 August Russell Van Nice and Michael Gold reported the same silhouette. Papers ran it. One later sceptical reconstruction points at a costume and a recant. The original police complaint is why the file survived the joke.",
    body: "A gill-man in a suburban lake in 1972 is either cinema leaking into a beach or a one-week occupant event. Loveland is the Ohio cousin. Neither produced a netted amphibian.",
    evidence: "Victoria police report as quoted in August 1972 press; second-day witnesses. No photograph of the figure.",
    sources: [
      "Victoria Times and Colonist, 21–22 August 1972",
      "Later recant / costume reconstructions",
    ],
    lat: 48.466,
    lng: -123.466,
    place: "Thetis Lake, Victoria",
    country: "Canada",
    year: 1972,
  },
  {
    id: "lake-worth-monster",
    title: "Lake Worth Monster",
    kicker: "1969",
    subtitle: "Greer Island, Texas · white goat-man",
    lede: "A Fort Worth park panic, a damaged car, and then a man who said it had been a costume. The first nights still sit in the Star-Telegram.",
    summary: "In July 1969, witnesses around Greer Island in Lake Worth, Texas, reported a large, white, goat-like biped. John Reichart’s car was damaged. Police and crowds showed up. The Fort Worth Star-Telegram put it on the front. A later confession — a prankster in white canvas — is the sceptical close. Not every witness signed onto the prank.",
    body: "A costume can start a park riot. It can also be a convenient confession after the fact. Keep the 1969 blotter and the admission in the same folder. Do not let either erase the other.",
    evidence: "Fort Worth Star-Telegram, July 1969; later hoax admissions. No specimen.",
    sources: [
      "Fort Worth Star-Telegram, July 1969",
      "Later published hoax/confession accounts",
    ],
    lat: 32.822,
    lng: -97.476,
    place: "Lake Worth, Texas",
    country: "USA",
    year: 1969,
  },
  {
    id: "yeren",
    title: "Yeren",
    kicker: "1976",
    subtitle: "Shennongjia, Hubei · Chinese wild-man",
    lede: "Provincial scientific expeditions treated a reddish biped as a survey problem. They came home with casts, hair, and no body.",
    summary: "Hubei’s Shennongjia forest produced decades of ‘wild-man’ (yeren) reports. In 1976–77 and later, Chinese scientific teams — some under provincial academy auspices — collected footprint casts, hair, and interviews. Official interest is why this file is heavier than a tourist legend. Golden snub-nosed monkeys and bears are the ordinary fauna. They are not a 2-metre biped unless the witnesses cannot count.",
    body: "A state-adjacent expedition that fails to produce a type specimen is still a data point: the reports were thick enough to spend money on. Hair that comes back as known mammals is the usual end. Orang-pendek is the Indonesian cousin with better fieldworkers still on the ground.",
    evidence: "1976–80s Chinese expedition reports as published; casts and hair samples later re-identified. No skeleton.",
    sources: [
      "Hubei / Shennongjia expedition summaries as published in the late 1970s–80s",
      "Later hair-sample reidentifications in the cryptozoological and mammalogical literature",
    ],
    lat: 31.47,
    lng: 110.39,
    place: "Shennongjia, Hubei",
    country: "China",
    year: 1976,
  },
  {
    id: "hibagon",
    title: "Hibagon",
    kicker: "1970",
    subtitle: "Mount Hiba, Hiroshima · Japanese ape-man",
    lede: "A four-year flap on a forested Hiroshima mountain. Police took casts. The ape did not walk into a lab in Shobara.",
    summary: "From 1970 to 1974, residents around Mount Hiba in Hiroshima Prefecture reported a 5-foot, snub-nosed, pungent ape-man — Hibagon. Town offices and police logged calls and took footprint casts. Japanese papers treated it as a domestic yeti. The flap ended. No body was produced.",
    body: "A short, well-dated municipal flap with casts is the Japanese hominid file. Bear and macaque are the fauna list. A snub-nosed biped with a terrible smell is the leftover.",
    evidence: "1970–74 Hiroshima prefectural and national press; police casts. No specimen.",
    sources: [
      "Chugoku Shimbun and national Japanese coverage, 1970–74",
      "Shobara municipal retrospectives",
    ],
    lat: 34.86,
    lng: 133.05,
    place: "Mount Hiba, Hiroshima",
    country: "Japan",
    year: 1972,
  },
  {
    id: "barmanou",
    title: "Barmanou",
    kicker: "1992",
    subtitle: "Chitral / Hindu Kush · Pakistani wild-man",
    lede: "Jordi Magraner spent years in Chitral collecting footprint and interview data on a local hairy hominid. He was murdered. The casts stayed.",
    summary: "Barmanou (or barmanu) is the Hindu Kush / Chitral wild-man of northern Pakistan. Spanish zoologist Jordi Magraner collected reports, casts, and hair through the 1990s. He was killed in Chitral in 2002. The file is interviews plus tracks in a region that already has bears and folklore. No type specimen reached a museum.",
    body: "A fieldworker who dies in-country is not proof of the animal. It is proof the study was not a weekend. Treat Magraner’s notes as the best Pakistani hominid paper, not as a holotype.",
    evidence: "Magraner field reports and casts as later circulated; local interview corpora. No skeleton.",
    sources: [
      "Jordi Magraner Chitral field reports, 1990s",
      "Press on Magraner’s 2002 death in Chitral",
    ],
    lat: 35.85,
    lng: 71.79,
    place: "Chitral, Pakistan",
    country: "Pakistan",
    year: 1992,
  },
  {
    id: "grey-man-macdui",
    title: "Grey Man of Ben Macdui",
    kicker: "1925",
    subtitle: "Cairngorms · Fear Liath Mòr",
    lede: "A chemist and mountaineer told the Cairngorm Club he had been followed by a large presence in the mist in 1891. He waited decades to say it out loud.",
    summary: "In 1925 Professor John Norman Collie told the Cairngorm Club of an 1891 experience on Ben Macdui: crunching steps in the mist, a sense of a large figure, a panicked descent. Other climbers later added encounters with Fear Liath Mòr, the Big Grey Man. Brocken spectres and hypoxia are the mountain answers. Collie was not a tourist.",
    body: "An atmospheric-optics file that happens to wear a Gaelic name. Or a presence tradition on Britain’s second summit. Dark Watchers are the California rhyme. No photograph of a body, plenty of photographs of Brocken spectres.",
    evidence: "Collie’s 1925 Cairngorm Club account; later climber reports. No physical trace.",
    sources: [
      "J. Norman Collie, Cairngorm Club address, 1925",
      "Later Cairngorm climbing memoirs",
    ],
    lat: 57.07,
    lng: -3.669,
    place: "Ben Macdui, Cairngorms",
    country: "UK",
    year: 1925,
  },
  {
    id: "storsjo",
    title: "Storsjöodjuret",
    kicker: "1894",
    subtitle: "Lake Storsjön, Sweden · legally protected serpent",
    lede: "A 19th-century catch company, then a 1986 county protection order. Sweden put a lake monster on the books. The animal still has not sat for a tag.",
    summary: "Lake Storsjön in Jämtland has a long serpent tradition. In 1894 a company was formed to catch Storsjöodjuret. In 1986 the Jämtland County Administrative Board listed the creature as protected; the protection was revoked in 2005 as lacking legal basis. Sonar, photographs, and a 2008 film expedition followed. The lake is real. The legal paper is real. The holotype is not.",
    body: "A government that protects an unverified animal is doing folklore-as-policy. That paper is why this file is confirmed as a record and disputed as a species. Nessie never got a statutory shield.",
    evidence: "1894 catch-company papers; 1986 protection and 2005 repeal; later sonar/film efforts. No specimen.",
    sources: [
      "Jämtland County Administrative Board protection (1986) and repeal (2005)",
      "1894 Storsjöodjuret catch-company records as later published",
    ],
    lat: 63.22,
    lng: 14.36,
    place: "Lake Storsjön, Jämtland",
    country: "Sweden",
    year: 1894,
  },
  {
    id: "nahuelito",
    title: "Nahuelito",
    kicker: "1922",
    subtitle: "Nahuel Huapi, Argentina · Patagonian lake animal",
    lede: "An American in 1922 described a plesiosaur-shaped animal in a glacial lake. Patagonia already had a lost-world brand. The lake did not yield a reptile.",
    summary: "Lago Nahuel Huapi produced 1922 reports — George Garrett among them — of a long-necked animal, later nicknamed Nahuelito. C. Reginald Enock and others fed a 1920s lost-world press cycle. Later photographs are logs and wakes. The lake is deep and oligotrophic. Tourism did the rest.",
    body: "Patagonia attracts extinct-animal stories because the map still looks empty from London. A 1922 letter is not a sonar track. File it with Champ and Tessie as the southern lake file.",
    evidence: "1922 press letters; later tourist photographs. No specimen.",
    sources: [
      "1922 English-language press letters on Nahuel Huapi",
      "Later Argentine press photograph cycles",
    ],
    lat: -41.09,
    lng: -71.57,
    place: "Lago Nahuel Huapi",
    country: "Argentina",
    year: 1922,
  },
  {
    id: "issie",
    title: "Issie",
    kicker: "1978",
    subtitle: "Lake Ikeda, Kagoshima · Japanese lake animal",
    lede: "A 1978 photograph of two dark humps in a caldera lake made a Japanese Nessie. Eels and carp already live there.",
    summary: "Lake Ikeda on Kyushu produced 1978 photographs of dark, humped objects that the press named Issie (from the lake, Ikeda). A tourist industry followed. The lake holds large eels and carp. No carcass of an unknown vertebrate has been landed. Japan’s other hominid file is Hibagon; this is the water one.",
    body: "A hump photograph on a caldera lake is a genre, not a capture. Keep Issie as the East Asian lake-monster type case.",
    evidence: "1978 Japanese press photographs; no specimen.",
    sources: [
      "Japanese national and Kagoshima press, 1978",
      "Later Lake Ikeda tourist-board material as cultural record",
    ],
    lat: 31.233,
    lng: 130.566,
    place: "Lake Ikeda, Kagoshima",
    country: "Japan",
    year: 1978,
  },
  {
    id: "tatzelwurm",
    title: "Tatzelwurm",
    kicker: "1779",
    subtitle: "Alps · stub-legged serpent",
    lede: "A Bavarian-Austrian cat-faced viper with tiny legs. Hans Fuchs of Unken is said to have died of the fright in 1779. The Alps never produced a skin.",
    summary: "The Tatzelwurm is the Alpine stub-limbed serpent: cat-like face, two or four small legs, two metres of pale body. The 1779 Unken story of Hans Fuchs is the dated rural core; Swiss and Austrian naturalists collected later sightings. Skinks, otters, and decaying logs do most of the work. A breeding unknown squamate in the Alps would have turned up in a ski cut.",
    body: "Alpine folklore with a Linnaean itch. File it next to Minhocão as a hidden elongate vertebrate that mining and mountaineering should have ended. They have not produced a jar.",
    evidence: "1779 Unken tradition as later recorded; 19th–20th century Alpine naturalist notes. No specimen.",
    sources: [
      "Unken / Salzburg regional accounts of the 1779 Fuchs story",
      "Alpine natural-history compilations of Tatzelwurm reports",
    ],
    lat: 47.649,
    lng: 12.729,
    place: "Unken, Salzburg",
    country: "Austria",
    year: 1779,
  },
  {
    id: "dobhar-chu",
    title: "Dobhar-chú",
    kicker: "1722",
    subtitle: "Glenade Lough, Leitrim · king otter",
    lede: "A graveslab at Conwal shows a long-bodied animal over a woman. The 1722 death of Grace Connolly is the dated Irish water-monster file.",
    summary: "Irish tradition of the dobhar-chú (‘water hound’) sits on a real 1722 stone: the grave of Grace (Grainne) Connolly at Conwal, near Glenade Lough, County Leitrim, carved with a long-necked beast. Local story says the animal killed her at the lough and was itself killed. Otter is the zoology. The slab is the artifact.",
    body: "A carved stone is better evidence than a 21st-century blog. It is still a stone, not a pelt. File the monument as confirmed and the animal as the question.",
    evidence: "Conwal graveslab (dated 1722 in local tradition); Leitrim oral history. No pelt.",
    sources: [
      "Conwal / Glenade graveslab of Grace Connolly",
      "County Leitrim folklore collections",
    ],
    lat: 54.366,
    lng: -8.268,
    place: "Glenade Lough, County Leitrim",
    country: "Ireland",
    year: 1722,
  },
  {
    id: "nandi-bear",
    title: "Nandi Bear",
    kicker: "1912",
    subtitle: "Uasin Gishu, Kenya · hyena that isn’t",
    lede: "Colonial officers described a high-shouldered, face-tearing predator in Nandi country. Spotted hyena is the default. It does not always fit the posture.",
    summary: "Early-20th-century Kenya produced reports — Geoffrey Williams in 1912 among them — of a bulky, bear-like, sometimes bipedal predator in the Nandi and Uasin Gishu highlands, accused of tearing faces from sleepers. Settlers called it the Nandi bear. Hyena, ratel, and aardvark all appear in the sceptical set. No skin of an unknown ursid was logged at Nairobi.",
    body: "Africa does not have bears. That sentence is why the file exists. A mis-seen hyena is the cheap close. A surviving chalicothere or unknown hyaenid is the expensive one. The colonial paper is uneven and racialized; read it as testimony, not as taxonomy.",
    evidence: "Williams 1912 and other East African settler/officer notes; no type specimen.",
    sources: [
      "Geoffrey Williams, 1912 Nandi-area account as later anthologized",
      "Colonial East African game notes",
    ],
    lat: 0.52,
    lng: 35.27,
    place: "Nandi / Uasin Gishu, Kenya",
    country: "Kenya",
    year: 1912,
  },
  {
    id: "ahool",
    title: "Ahool",
    kicker: "1925",
    subtitle: "Java · giant bat",
    lede: "A naturalist’s son on Mount Salak described a monkey-faced bat with a twelve-foot span that called ahooool. Flying foxes are large. They are not that large.",
    summary: "In 1925 Dr. Ernest Bartels reported a giant, dark, monkey-faced bat by a river on the slopes of Mount Salak, Java — the ahool, named for its cry. Later Indonesian reports are thin. The large flying foxes of the region top out well under the claimed span. A mis-seen eagle or a very large Pteropus is the ordinary bet. A twelve-foot chiropteran is not on the island list.",
    body: "One good 1925 note plus a name. That is most Asian flying-cryptid files. Ropen is the New Guinea cousin with a bioluminescent twist. Neither has a skin in Bogor or Port Moresby.",
    evidence: "Bartels 1925 account as later published; no specimen.",
    sources: [
      "Ernest Bartels Mount Salak account, 1925, as later cited",
      "Regional flying-fox natural history",
    ],
    lat: -6.713,
    lng: 106.734,
    place: "Mount Salak, Java",
    country: "Indonesia",
    year: 1925,
  },
  {
    id: "ropen",
    title: "Ropen",
    kicker: "1994",
    subtitle: "Umboi Island · luminous flyer",
    lede: "New Guinea islanders described a long-tailed nocturnal glider that sometimes glowed. American creationist expeditions went looking for a living pterosaur. They brought back interviews.",
    summary: "On Umboi and neighbouring islands of Papua New Guinea, rumours of a large, long-tailed, sometimes bioluminescent flyer — ropen — drew 1990s–2000s American expeditions. Witness drawings look like a pterosaur because the interviewers asked in that language. Frigatebirds, flying foxes, and meteors do ordinary work at night. A surviving azhdarchid does not, on present bones.",
    body: "This file is a warning about leading questions as much as it is a creature file. Keep the islander reports. Discount the Western overlay that already knew what it wanted to find.",
    evidence: "Expedition interview corpora (Whitcomb and others); no specimen, no unambiguous photograph.",
    sources: [
      "1990s–2000s Umboi expedition reports",
      "Papua New Guinea island oral-history notes as published by those teams",
    ],
    lat: -5.65,
    lng: 147.87,
    place: "Umboi Island",
    country: "Papua New Guinea",
    year: 1994,
  },
  {
    id: "thylacine",
    title: "Thylacine after 1936",
    kicker: "1936–",
    subtitle: "Tasmania · the animal the zoo buried",
    lede: "The last captive died in Hobart on 7 September 1936. The bush did not sign the certificate. Camera traps keep almost catching one.",
    summary: "Benjamin, the last zoo thylacine, died in Hobart in 1936. Tasmania still produces tracks, night photos, and the 1982 Hans Naarding sighting — a trained parks officer, at close range, at night. Mainland reports are a separate, weaker set. eDNA surveys have been suggestive and unreplicated. A living breeding population would be the conservation story of the century. It has not sat in a trap.",
    body: "This is the rare cryptid file where the species is not in dispute — only its death date. That makes the standard of evidence higher, not lower. A blur is not a resurrection. A parks officer is not nothing.",
    evidence: "Hobart Zoo death record, 1936; Naarding 1982 report to Tasmanian Parks; later camera-trap and eDNA claims still unconfirmed as a population.",
    sources: [
      "Hobart Zoo / Tasmanian museum records of the 1936 death",
      "Hans Naarding, 1982 report to Tasmanian National Parks",
      "Later eDNA and camera-trap surveys as published",
    ],
    lat: -41.45,
    lng: 145.97,
    place: "Arthur River / northwest Tasmania",
    country: "Australia",
    year: 1982,
  },
  {
    id: "deloys-ape",
    title: "De Loys’ ape",
    kicker: "1920",
    subtitle: "Sierra de Perijá · propped spider monkey",
    lede: "A 1920 photograph of a tailless-looking primate on a crate. Montandon named a species. Most zoologists named a spider monkey and a knife.",
    summary: "François de Loys, on a 1917–20 oil expedition in the Sierra de Perijá, photographed a dead primate sat on a crate. In 1929 George Montandon published it as Ameranthropoides loysi, a South American ape. The consensus is a spider monkey with the tail out of frame or removed. The crate supplies no scale you can trust. No skull was lodged in a museum as the holotype.",
    body: "A photograph that wants to be a new family of primates. Count the tail. Count the crate. File it as a lesson in how a cryptid is manufactured from a carcass you already know.",
    evidence: "The 1920 photograph; Montandon 1929 paper; later spider-monkey identifications.",
    sources: [
      "George Montandon, 1929 description of Ameranthropoides loysi",
      "François de Loys expedition notes as later published",
      "Subsequent primatological reidentifications as Ateles",
    ],
    lat: 9.3,
    lng: -73.0,
    place: "Sierra de Perijá",
    country: "Venezuela",
    year: 1920,
  },
  {
    id: "bossburg",
    title: "Bossburg Cripplefoot",
    kicker: "1969",
    subtitle: "Washington · clubfooted tracks",
    lede: "A set of Sasquatch prints with one deformed foot, touted as too weird to fake. Ivan Marx was in the picture. Later opinion soured.",
    summary: "In 1969, near Bossburg, Washington, a line of large footprints included a right foot with a clubbed, twisted morphology — ‘Cripplefoot.’ René Dahinden and others studied the casts. A crippled foot was supposed to be the detail a hoaxer would not invent. Later researchers, including some who had been friendly to the case, treated Marx’s involvement as disqualifying. The casts still exist.",
    body: "Anomalous anatomy is only evidence if the track maker is not a carver. File the casts as objects. File the clubfoot argument as a logic that did not survive its witnesses.",
    evidence: "1969 casts; Dahinden notes; later hoax-leaning reconstructions. No body.",
    sources: [
      "1969 Bossburg casts and contemporary notes",
      "René Dahinden case materials",
      "Later sceptical reconstructions of Ivan Marx’s role",
    ],
    lat: 48.78,
    lng: -118.02,
    place: "Bossburg, Washington",
    country: "USA",
    year: 1969,
  },
  {
    id: "jacko",
    title: "Jacko of Yale",
    kicker: "1884",
    subtitle: "British Columbia · ape on the rails",
    lede: "The Daily British Colonist said a small gorilla-like animal was captured at Yale on the Canadian Pacific. No zoo ever logged the intake.",
    summary: "On 4 July 1884 the Daily British Colonist in Victoria reported that a hairy, gorilla-like juvenile — Jacko — had been taken alive near Yale, B.C., after railroad workers stunned it. The paper described it in a cage bound for the circus circuit. No subsequent institution acknowledged receipt. Most historians now read it as a slow-news invention. It remains the 19th-century Pacific Northwest capture story.",
    body: "A single newspaper capture with no downstream paperwork is a hoax until proven otherwise. It is also the template every later Sasquatch capture rumour copies. Keep the clipping. Do not keep a body that never arrived.",
    evidence: "Daily British Colonist, 4 July 1884; absence of any zoo or circus intake. No photograph, no skeleton.",
    sources: [
      "Daily British Colonist, Victoria, 4 July 1884",
      "Later historical reviews of the Jacko clipping",
    ],
    lat: 49.561,
    lng: -121.43,
    place: "Yale, British Columbia",
    country: "Canada",
    year: 1884,
  },
  {
    id: "trunko",
    title: "Trunko",
    kicker: "1924",
    subtitle: "Margate, Natal · white-trunked globster",
    lede: "Witnesses said a white, trunked animal fought two whales, then washed up. The photographs, found decades later, look like a decomposed whale.",
    summary: "On 25 October 1924, observers at Margate, South Africa, described a white, furred, trunk-faced carcass after an alleged fight with two whales. The animal was dubbed Trunko. Photographs rediscovered in the 2010s show a classic globster — a whale whose decayed tissue reads as fur and a trunk. No unique mammal was taxidermied.",
    body: "Zuiyō-maru is the Pacific cousin: a real carcass, a wrong animal. File Trunko as the Atlantic lesson in decay, not as a polar bear in Natal.",
    evidence: "1924 Natal press; later-published photographs identified as a decomposed cetacean.",
    sources: [
      "Natal / Rand Daily Mail coverage, October 1924",
      "Later-published Margate carcass photographs and globster analyses",
    ],
    lat: -30.863,
    lng: 30.37,
    place: "Margate, Natal",
    country: "South Africa",
    year: 1924,
  },
  {
    id: "sucuriju",
    title: "Sucuriju gigante",
    kicker: "1907",
    subtitle: "Amazon · giant anaconda claims",
    lede: "Percy Fawcett wrote of a 62-foot snake. Amazonian sucuriju stories are older. A verified skin over 10 metres has not landed in a museum.",
    summary: "Colonel Percy Fawcett’s 1907 Amazon notes describe shooting a giant anaconda on a river — the most famous Western sucuriju gigante claim. Rubber-era and later Brazilian reports go longer still. The record measured Eunectes murinus skins sit well below the 60-foot class. Surveys continue. A breeding 18-metre serpent would be hard to miss in the 21st-century Amazon. Hard is not impossible. It is not a holotype either.",
    body: "River men exaggerate length. Naturalists under-sample oxbows. Both can be true. Keep Fawcett as a primary with a reputation for colour, not as a tape measure.",
    evidence: "Fawcett 1907 notes as later published; museum anaconda maxima. No verified 60-foot skin.",
    sources: [
      "Percy Fawcett expedition notes (1907) as later published",
      "Museum measured maxima for Eunectes murinus",
    ],
    lat: -9.7,
    lng: -65.5,
    place: "Rio Abuná / western Amazon",
    country: "Brazil",
    year: 1907,
  },
  {
    id: "piasa",
    title: "Piasa",
    kicker: "1673",
    subtitle: "Alton bluffs · painted flyer",
    lede: "Marquette described a painted monster on the Mississippi cliffs. The rock is real. The current painting is a reconstruction. The animal was never a specimen.",
    summary: "In 1673 Jacques Marquette and Louis Jolliet recorded a large painted figure on the bluffs near present-day Alton, Illinois — a winged, horned, scale-bodied creature later called the Piasa. Illini traditions sit behind the image. The original painting was destroyed by quarry and time; later restorations are civic art. The 1673 journal is the primary.",
    body: "This is a rock-art file first, a cryptid second. Thunderbird is the living-sky cousin. Do not promote a bluff painting into a flock.",
    evidence: "Marquette 1673 journal description; later Alton restorations as civic copies. No bones.",
    sources: [
      "Jacques Marquette, 1673 journal",
      "Alton, Illinois historical reconstructions of the Piasa painting",
    ],
    lat: 38.889,
    lng: -90.175,
    place: "Alton, Illinois",
    country: "USA",
    year: 1673,
  },
  {
    id: "hodag",
    title: "Hodag",
    kicker: "1893",
    subtitle: "Rhinelander, Wisconsin · admitted hoax",
    lede: "Eugene Shepard carved a monster, photographed it, and later said so. Rhinelander kept the mascot. The file is how a cryptid is born on purpose.",
    summary: "In 1893 lumberman Eugene Shepard of Rhinelander, Wisconsin, reported a horned, fanged, spike-backed animal — the hodag. A 1896 ‘capture’ was shown in a dim shed. Shepard later admitted a wood-and-ox-hide fake. The town still uses the name. This is the control sample: a known manufactured cryptid with a paper trail.",
    body: "Keep Hodag next to Jacko and De Loys as manufacturing methods. When a later file has no Shepard and no admission, do not pretend this one proves they are all fake. It proves this one was.",
    evidence: "1893–96 Rhinelander press; Shepard’s later admission; surviving photographs of the fake.",
    sources: [
      "Rhinelander press, 1893–96",
      "Eugene Shepard’s later admission as recorded locally",
    ],
    lat: 45.636,
    lng: -89.412,
    place: "Rhinelander, Wisconsin",
    country: "USA",
    year: 1893,
  },
  {
    id: "onza",
    title: "Onza",
    kicker: "1986",
    subtitle: "Sinaloa · extra Mexican cat",
    lede: "Ranchers shot a long-legged puma-like cat near San Ignacio. DNA said puma. The folk taxon did not die on the slab.",
    summary: "On 16 January 1986 a large, rangy felid was killed on a ranch near San Ignacio, Sinaloa, and offered as the onza — a Mexican folk cat distinct from puma and jaguar. Measurements and photographs circulated. Later genetic work identified Puma concolor. Regional reports of a slimmer, meaner cat continue. A folk name can outlive a genotype.",
    body: "This is what a resolved cryptid looks like: a body, a lab, a known species. Keep it on the desk as the calibration file for every later ‘unknown cat’ — Bodmin included.",
    evidence: "1986 San Ignacio carcass photographs and measurements; subsequent DNA as puma.",
    sources: [
      "1986 Sinaloa carcass reports and photographs",
      "Later genetic identifications as Puma concolor",
    ],
    lat: 23.94,
    lng: -106.42,
    place: "San Ignacio, Sinaloa",
    country: "Mexico",
    year: 1986,
  },
  {
    id: "marozi",
    title: "Marozi / spotted lion",
    kicker: "1931",
    subtitle: "Aberdares, Kenya · highland lion",
    lede: "A farmer shot two spotted lions in the Aberdare highlands. A skin reached London. Most zoologists now say juvenile or highland morph, not a species.",
    summary: "In 1931 Michael Trent killed two unusually spotted lions on the Aberdare highlands of Kenya. A skin went to the Natural History Museum. Game officers collected further highland reports of a smaller, spotted ‘marozi.’ The cheap close is subadult Panthera leo or a local morph. A separate highland species has no living population on the books.",
    body: "A skin in a drawer is more than a rumour and less than a new lion. Onza is the New World rhyme: folk taxon, known genome. The Aberdare skin has not been re-sold as a new species in a current revision.",
    evidence: "1931 Trent skin as later held/described; game-department notes. No wild breeding population under a separate name.",
    sources: [
      "1931 Aberdare skin and game reports as later published",
      "Natural History Museum lion-skin notes as cited in the cryptozoological literature",
    ],
    lat: -0.38,
    lng: 36.7,
    place: "Aberdare Range, Kenya",
    country: "Kenya",
    year: 1931,
  },
];
