/** Real desk-to-desk relations. Only ids that exist as files; no guessed matches. */
const CLUSTERS: string[][] = [
  // Conspiracy
  ["majestic-12", "hangar-18", "dulce", "magenta-1933"],
  ["area-51", "s4-lazar", "egg-g", "hangar-18", "skunk-works-uap"],
  ["bennewitz", "dulce", "men-in-black"],
  ["blue-book", "project-sign", "project-grudge", "estimate-of-situation", "condon-committee", "robertson-panel", "hynek-cufos"],
  ["project-sign", "estimate-of-situation", "project-grudge"],
  ["aatip", "aawsap", "nyt-2017", "ttsa", "elizondo-title", "five-observables", "mellon-drop"],
  ["aawsap", "baass-report", "nids", "kona-blue", "hitchhiker-effect"],
  ["nyt-2017", "fravor-testimony", "gimbal-glare", "gofast-debate", "roosevelt-incursions"],
  ["grusch", "wilson-davis", "legacy-program", "immaculate-constellation", "uap-disclosure-act", "burchett-hearings"],
  ["uap-disclosure-act", "gillibrand", "burchett-hearings"],
  ["odni-2021", "uaptf", "nasa-uap-panel", "aaro-historical", "pursue-war-gov"],
  ["pursue-war-gov", "aaro-historical", "kirkpatrick"],
  ["flying-saucer-working-party", "condign", "uk-files-release", "nick-pope"],
  ["project-magnet", "second-storey", "wilbert-smith-memo"],
  ["geipan", "cometa"],
  ["galileo-project", "oumuamua", "im1-spherules"],
  ["nazca-mummies", "maussan-congress", "atacama-mummy"],
  ["hopkins-intruders", "strieber-communion", "linda-cortile", "andreasson", "peer-mack"],
  ["malmstrom-cover", "nuclear-correlation"],
  ["stargate-rv", "montauk"],
  ["adamski", "contactee-giant-rock"],
  ["cia-haines", "fbi-vault", "robertson-panel"],
  ["men-in-black", "maury-island", "bennewitz", "fbi-vault", "nicap-keyhoe", "hopkins-intruders"],
  ["nj-drones-2024", "chinese-balloon"],
  // Cryptids / Fortean (conspiracy desk)
  ["bigfoot", "patterson-gimlin", "ape-canyon", "skunk-ape", "fouke-monster", "honey-island", "cryptoterrestrial"],
  ["bigfoot", "momo", "grassman", "mud-monster", "minnesota-iceman", "bossburg", "jacko"],
  ["yeti", "orang-pendek", "almasty", "yowie", "mapinguari", "yeren", "hibagon", "barmanou"],
  ["yeti", "bigfoot", "orang-pendek", "yeren"],
  ["mothman", "silver-bridge", "indrid-cold", "owlman", "flatwoods-monster", "grafton-monster", "van-meter"],
  ["flatwoods-monster", "flatwoods", "kelly-goblins", "kelly-hopkinsville", "dover-demon"],
  ["kelly-goblins", "kelly-hopkinsville", "hopkins-intruders"],
  ["jersey-devil", "spring-heeled-jack", "pope-lick", "goatman", "snallygaster", "hodag"],
  ["lizard-man", "loveland-frog", "thetis-lake", "lake-worth-monster"],
  ["chupacabra", "cattle-mutilations", "montauk-monster"],
  ["bray-road", "michigan-dogman", "enfield-horror"],
  ["thunderbird", "batsquatch", "piasa", "ropen", "ahool"],
  ["mothman", "thunderbird", "batsquatch", "owlman"],
  ["nessie", "champ", "ogopogo", "cadborosaurus", "bunyip", "zuiyo-maru"],
  ["champ", "tahoe-tessie", "chessie", "altamaha-ha"],
  ["nessie", "storsjo", "nahuelito", "issie"],
  ["cadborosaurus", "zuiyo-maru", "trunko"],
  ["mokele-mbembe", "kongamato", "minhocao", "mongolian-death-worm"],
  ["mokele-mbembe", "nandi-bear", "marozi"],
  ["minhocao", "sucuriju", "tatzelwurm", "dobhar-chu"],
  ["beast-gevaudan", "beast-bodmin", "onza"],
  ["montauk-monster", "montauk"],
  ["skinwalker-ranch", "aawsap", "hitchhiker-effect", "nids", "baass-report", "cattle-mutilations"],
  ["aawsap", "hitchhiker-effect", "thunderbird", "bray-road", "skinwalker-ranch"],
  ["dark-watchers", "grey-man-macdui", "earthlights"],
  ["thylacine", "yowie", "bunyip"],
  ["deloys-ape", "minnesota-iceman", "jacko", "hodag"],
  ["jersey-devil", "snallygaster"],
  // Ancient / contact
  ["giza", "sphinx", "bent-pyramid", "osirion", "serapeum", "osiris-shaft", "pyramid-texts-stars"],
  ["nazca", "acre-geoglyphs", "atacama-giant", "blythe-intaglios", "paracas-skulls"],
  ["gobekli", "karahan-tepe", "nevali-cori"],
  ["puma-punku", "gate-of-the-sun", "sacsayhuaman", "viracocha-andes"],
  ["sacsayhuaman", "ollantaytambo", "machu-picchu", "coricancha"],
  ["moai", "vinapu", "nan-madol", "haamonga"],
  ["ggantija", "mnajdra", "hagar-qim", "hypogeum"],
  ["stonehenge", "avebury", "silbury", "newgrange", "knowth"],
  ["derinkuyu", "kaymakli"],
  ["baalbek", "pregnant-stone"],
  ["teotihuacan", "cholula", "olmec-heads"],
  ["atlantis-plato", "bimini-road", "richat", "piri-reis", "hapgood-maps"],
  ["anunnaki-eridu", "anunnaki-council", "enki-me", "enlil-nippur", "nibiru-sitchin", "apkallu-sages", "oannes-berossus"],
  ["watchers-enoch", "hermon-descent", "nephilim", "azazel-arts", "book-of-giants", "genesis-6", "jubilees-watchers", "dead-sea-enoch", "shemihazah"],
  ["viracocha-andes", "quetzalcoatl-teacher"],
  ["osiris-civilizer", "thoth-teacher", "edfu-texts", "pyramid-texts-stars"],
  ["ezekiel-wheels", "elijah-chariot"],
  ["vimana", "sakwala"],
  // Archive map ↔ Conspiracy (bidirectional)
  ["roswell", "majestic-12", "hangar-18", "moon-dust", "magenta-1933"],
  ["aztec-nm", "majestic-12", "hangar-18"],
  ["trinity-san-antonio", "majestic-12", "hangar-18"],
  ["cape-girardeau", "hangar-18", "moon-dust"],
  ["kingman-az", "hangar-18", "area-51"],
  ["kecksburg", "moon-dust", "hangar-18"],
  ["needles-2008", "moon-dust", "hangar-18"],
  ["holloman-landing", "area-51", "majestic-12"],
  ["kenneth-arnold", "project-sign", "nicap-keyhoe"],
  ["maury-island", "project-sign", "cia-haines", "men-in-black"],
  ["mantell", "project-sign", "project-grudge", "blue-book"],
  ["foo-fighters", "project-sign"],
  ["ghost-rockets", "project-sign"],
  ["battle-of-los-angeles", "project-sign", "fbi-vault"],
  ["green-fireballs", "project-twinkle"],
  ["washington-flap", "robertson-panel", "blue-book", "cia-haines", "fbi-vault"],
  ["lubbock-lights", "blue-book"],
  ["socorro", "blue-book", "hynek-cufos"],
  ["rb-47", "blue-book", "condon-committee"],
  ["exeter", "blue-book", "hynek-cufos"],
  ["dexter-hillsdale", "hynek-cufos", "condon-committee"],
  ["farmington-armada", "blue-book"],
  ["kadena-1952", "blue-book"],
  ["fukuoka-1948", "project-sign"],
  ["nimitz", "aatip", "nyt-2017", "fravor-testimony", "five-observables", "grusch", "wilson-davis", "legacy-program"],
  ["gimbal", "gimbal-glare", "aatip", "nyt-2017", "gofast-debate"],
  ["aguadilla", "transmedium-uso", "aatip"],
  ["etna-aaro", "aaro-historical", "pursue-war-gov"],
  ["eglin-2023", "aaro-historical", "odni-2021"],
  ["mosul-orb", "aatip", "five-observables"],
  ["langley-drones", "nj-drones-2024", "chinese-balloon"],
  ["malmstrom", "malmstrom-cover", "nuclear-correlation"],
  ["minot-afb", "nuclear-correlation"],
  ["northern-tier", "nuclear-correlation"],
  ["wurtsmith", "nuclear-correlation"],
  ["hanford-1945", "nuclear-correlation"],
  ["oak-ridge-1950", "nuclear-correlation"],
  ["cash-landrum", "nuclear-correlation"],
  ["rendlesham", "nick-pope", "uk-files-release"],
  ["lakenheath", "condon-committee", "uk-files-release"],
  ["calvine", "uk-files-release", "nick-pope"],
  ["cosford", "uk-files-release"],
  ["colares", "operacao-prato-file"],
  ["varginha", "operacao-prato-file"],
  ["villas-boas", "operacao-prato-file"],
  ["brazil-1986", "operacao-prato-file"],
  ["barra-da-tijuca", "operacao-prato-file"],
  ["trindade", "operacao-prato-file"],
  ["chile-cefaa", "cefaa-office"],
  ["putre", "cefaa-office"],
  ["hessdalen", "hessdalen-project"],
  ["belgium-wave", "de-brouwer", "cometa"],
  ["valensole", "geipan", "cometa"],
  ["trans-en-provence", "geipan"],
  ["manises", "geipan"],
  ["nancy-amarante", "geipan"],
  ["ariel-school", "hopkins-intruders", "peer-mack"],
  ["hill-abduction", "hopkins-intruders", "strieber-communion"],
  ["travis-walton", "hopkins-intruders"],
  ["pascagoula", "hopkins-intruders"],
  ["kelly-hopkinsville", "hopkins-intruders"],
  ["flatwoods", "hopkins-intruders"],
  ["father-gill", "contactee-giant-rock"],
  ["phoenix-lights", "area-51"],
  ["edwards-afb", "area-51", "skunk-works-uap"],
  ["shag-harbour", "transmedium-uso"],
  ["catalina-uso", "transmedium-uso"],
  ["baikal-divers", "transmedium-uso"],
  ["buga-sphere", "metamaterials", "garry-nolan"],
  ["ubatuba", "metamaterials"],
  ["ohare", "narcap"],
  ["jal-1628", "five-observables"],
  ["xiaoshan", "five-observables"],
  ["india-iaf", "five-observables"],
  ["korea-adf", "five-observables"],
  ["japan-mod-uap", "odni-2021"],
  ["clark-ab", "moon-dust"],
  ["iwakuni", "moon-dust"],
  ["warminster", "crop-circles"],
  ["tully-nests", "crop-circles"],
  ["mexico-eclipse", "maussan-congress"],
  ["voronezh", "setka"],
  ["petrozavodsk", "setka"],
  ["dalnegorsk", "setka"],
  ["kapustin-yar", "setka"],
  ["tehran", "blue-book"],
  // Archive / Conspiracy ↔ Ancient
  ["nazca", "nazca-mummies", "paracas-skulls", "maussan-congress"],
  ["atacama-giant", "atacama-mummy"],
  ["mexico-eclipse", "teotihuacan", "chichen-equinox"],
  ["buga-sphere", "quimbaya"],
  ["putre", "viracocha-andes"],
  ["jodhpur", "vimana", "sakwala"],
];

function buildMap() {
  const map = new Map<string, Set<string>>();
  const add = (from: string, to: string) => {
    if (!from || !to || from === to) return;
    let set = map.get(from);
    if (!set) {
      set = new Set();
      map.set(from, set);
    }
    set.add(to);
  };
  for (const cluster of CLUSTERS) {
    for (const a of cluster) {
      for (const b of cluster) add(a, b);
    }
  }
  const out: Record<string, string[]> = {};
  for (const [id, set] of map) out[id] = [...set];
  return out;
}

export const RELATED_BY_ID: Record<string, string[]> = buildMap();
