/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeskRouteImport } from './routes/_desk'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as DeskAncientRouteImport } from './routes/_desk/ancient'
import { Route as DeskArchiveRouteImport } from './routes/_desk/archive'
import { Route as DeskArticlesRouteImport } from './routes/_desk/articles'
import { Route as DeskConspiracyRouteImport } from './routes/_desk/conspiracy'
import { Route as DeskSupportRouteImport } from './routes/_desk/support'
import { Route as DeskThePoleRouteImport } from './routes/_desk/the-pole'
import { Route as DeskXFilesRouteImport } from './routes/_desk/x-files'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/_desk',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskAncientRoute = DeskAncientRouteImport.update({
  id: '/ancient',
  path: '/ancient',
  getParentRoute: () => DeskRoute,
} as any)
const DeskArchiveRoute = DeskArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => DeskRoute,
} as any)
const DeskArticlesRoute = DeskArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => DeskRoute,
} as any)
const DeskConspiracyRoute = DeskConspiracyRouteImport.update({
  id: '/conspiracy',
  path: '/conspiracy',
  getParentRoute: () => DeskRoute,
} as any)
const DeskSupportRoute = DeskSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DeskRoute,
} as any)
const DeskThePoleRoute = DeskThePoleRouteImport.update({
  id: '/the-pole',
  path: '/the-pole',
  getParentRoute: () => DeskRoute,
} as any)
const DeskXFilesRoute = DeskXFilesRouteImport.update({
  id: '/x-files',
  path: '/x-files',
  getParentRoute: () => DeskRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/scan': typeof ScanRoute
  '/ancient': typeof DeskAncientRoute
  '/archive': typeof DeskArchiveRoute
  '/articles': typeof DeskArticlesRoute
  '/conspiracy': typeof DeskConspiracyRoute
  '/support': typeof DeskSupportRoute
  '/the-pole': typeof DeskThePoleRoute
  '/x-files': typeof DeskXFilesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/scan': typeof ScanRoute
  '/ancient': typeof DeskAncientRoute
  '/archive': typeof DeskArchiveRoute
  '/articles': typeof DeskArticlesRoute
  '/conspiracy': typeof DeskConspiracyRoute
  '/support': typeof DeskSupportRoute
  '/the-pole': typeof DeskThePoleRoute
  '/x-files': typeof DeskXFilesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_desk': typeof DeskRouteWithChildren
  '/login': typeof LoginRoute
  '/scan': typeof ScanRoute
  '/_desk/ancient': typeof DeskAncientRoute
  '/_desk/archive': typeof DeskArchiveRoute
  '/_desk/articles': typeof DeskArticlesRoute
  '/_desk/conspiracy': typeof DeskConspiracyRoute
  '/_desk/support': typeof DeskSupportRoute
  '/_desk/the-pole': typeof DeskThePoleRoute
  '/_desk/x-files': typeof DeskXFilesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/scan'
    | '/ancient'
    | '/archive'
    | '/articles'
    | '/conspiracy'
    | '/support'
    | '/the-pole'
    | '/x-files'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/scan'
    | '/ancient'
    | '/archive'
    | '/articles'
    | '/conspiracy'
    | '/support'
    | '/the-pole'
    | '/x-files'
  id:
    | '__root__'
    | '/'
    | '/_desk'
    | '/login'
    | '/scan'
    | '/_desk/ancient'
    | '/_desk/archive'
    | '/_desk/articles'
    | '/_desk/conspiracy'
    | '/_desk/support'
    | '/_desk/the-pole'
    | '/_desk/x-files'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeskRoute: typeof DeskRouteWithChildren
  LoginRoute: typeof LoginRoute
  ScanRoute: typeof ScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_desk': {
      id: '/_desk'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_desk/ancient': {
      id: '/_desk/ancient'
      path: '/ancient'
      fullPath: '/ancient'
      preLoaderRoute: typeof DeskAncientRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/archive': {
      id: '/_desk/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof DeskArchiveRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/articles': {
      id: '/_desk/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof DeskArticlesRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/conspiracy': {
      id: '/_desk/conspiracy'
      path: '/conspiracy'
      fullPath: '/conspiracy'
      preLoaderRoute: typeof DeskConspiracyRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/support': {
      id: '/_desk/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof DeskSupportRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/the-pole': {
      id: '/_desk/the-pole'
      path: '/the-pole'
      fullPath: '/the-pole'
      preLoaderRoute: typeof DeskThePoleRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/x-files': {
      id: '/_desk/x-files'
      path: '/x-files'
      fullPath: '/x-files'
      preLoaderRoute: typeof DeskXFilesRouteImport
      parentRoute: typeof DeskRoute
    }
  }
}

interface DeskRouteChildren {
  DeskAncientRoute: typeof DeskAncientRoute
  DeskArchiveRoute: typeof DeskArchiveRoute
  DeskArticlesRoute: typeof DeskArticlesRoute
  DeskConspiracyRoute: typeof DeskConspiracyRoute
  DeskSupportRoute: typeof DeskSupportRoute
  DeskThePoleRoute: typeof DeskThePoleRoute
  DeskXFilesRoute: typeof DeskXFilesRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskAncientRoute: DeskAncientRoute,
  DeskArchiveRoute: DeskArchiveRoute,
  DeskArticlesRoute: DeskArticlesRoute,
  DeskConspiracyRoute: DeskConspiracyRoute,
  DeskSupportRoute: DeskSupportRoute,
  DeskThePoleRoute: DeskThePoleRoute,
  DeskXFilesRoute: DeskXFilesRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeskRoute: DeskRouteWithChildren,
  LoginRoute: LoginRoute,
  ScanRoute: ScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
